import type { ChartOfAccountsTemplateRow } from '../types';

/**
 * Indian chart of accounts seeded when an IN entity is created.
 * GST control accounts use CGST/SGST/IGST system roles for place-of-supply posting.
 * AR (1300) / AP (1600) / revenue (8000) codes align with the shared finalize path.
 */
export const inChartOfAccounts: ChartOfAccountsTemplateRow[] = [
  // Assets
  { code: '1000', name: 'Fixed assets', type: 'asset', subtype: 'fixed_assets', normalSide: 'debit' },
  { code: '1100', name: 'Cash', type: 'asset', subtype: 'cash', normalSide: 'debit' },
  { code: '1200', name: 'Bank', type: 'asset', subtype: 'bank', normalSide: 'debit' },
  {
    code: '1300',
    name: 'Accounts receivable',
    type: 'asset',
    subtype: 'accounts_receivable',
    normalSide: 'debit',
    isSystemAccount: true,
    systemRole: 'accounts_receivable',
  },
  { code: '1400', name: 'Prepaid expenses', type: 'asset', subtype: 'current_assets', normalSide: 'debit' },
  { code: '1500', name: 'Inventory', type: 'asset', subtype: 'current_assets', normalSide: 'debit' },
  {
    code: '1510',
    name: 'Input CGST',
    type: 'asset',
    subtype: 'tax',
    normalSide: 'debit',
    isSystemAccount: true,
    systemRole: 'tax_input_cgst',
  },
  {
    code: '1520',
    name: 'Input SGST',
    type: 'asset',
    subtype: 'tax',
    normalSide: 'debit',
    isSystemAccount: true,
    systemRole: 'tax_input_sgst',
  },
  {
    code: '1530',
    name: 'Input IGST',
    type: 'asset',
    subtype: 'tax',
    normalSide: 'debit',
    isSystemAccount: true,
    systemRole: 'tax_input_igst',
  },
  {
    code: '1540',
    name: 'Input GST (legacy/combined)',
    type: 'asset',
    subtype: 'tax',
    normalSide: 'debit',
    isSystemAccount: true,
    systemRole: 'tax_input',
  },

  // Liabilities
  {
    code: '1600',
    name: 'Accounts payable',
    type: 'liability',
    subtype: 'accounts_payable',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'accounts_payable',
  },
  {
    code: '1700',
    name: 'GST payable',
    type: 'liability',
    subtype: 'tax',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'tax_payable',
  },
  {
    code: '1710',
    name: 'Output CGST',
    type: 'liability',
    subtype: 'tax',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'tax_output_cgst',
  },
  {
    code: '1720',
    name: 'Output SGST',
    type: 'liability',
    subtype: 'tax',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'tax_output_sgst',
  },
  {
    code: '1730',
    name: 'Output IGST',
    type: 'liability',
    subtype: 'tax',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'tax_output_igst',
  },
  {
    code: '1740',
    name: 'Output GST standard',
    type: 'liability',
    subtype: 'tax',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'tax_output_standard',
  },
  {
    code: '1750',
    name: 'Output GST reduced',
    type: 'liability',
    subtype: 'tax',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'tax_output_reduced',
  },
  { code: '1800', name: 'TDS payable', type: 'liability', subtype: 'tax', normalSide: 'credit' },
  { code: '1900', name: 'Accrued expenses', type: 'liability', subtype: 'accounts_payable', normalSide: 'credit' },
  { code: '2000', name: 'Long-term loans', type: 'liability', subtype: 'accounts_payable', normalSide: 'credit' },

  // Equity
  { code: '0500', name: 'Share capital', type: 'equity', subtype: 'capital', normalSide: 'credit' },
  { code: '0510', name: 'Reserves and surplus', type: 'equity', subtype: 'retained_earnings', normalSide: 'credit' },
  {
    code: '0530',
    name: 'Retained earnings',
    type: 'equity',
    subtype: 'retained_earnings',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'retained_earnings',
  },
  { code: '0540', name: 'Drawings', type: 'equity', subtype: 'capital', normalSide: 'debit' },

  // Revenue
  {
    code: '8000',
    name: 'Sales',
    type: 'revenue',
    subtype: 'other_income',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'sales_revenue',
  },
  { code: '8010', name: 'Sales — goods', type: 'revenue', subtype: 'other_income', normalSide: 'credit' },
  { code: '8020', name: 'Sales — services', type: 'revenue', subtype: 'other_income', normalSide: 'credit' },
  { code: '8100', name: 'Other income', type: 'revenue', subtype: 'other_income', normalSide: 'credit' },
  {
    code: '8400',
    name: 'Foreign exchange gain',
    type: 'revenue',
    subtype: 'other_income',
    normalSide: 'credit',
    isSystemAccount: true,
    systemRole: 'realized_fx_gain',
  },
  { code: '8500', name: 'Discount allowed', type: 'revenue', subtype: 'other_income', normalSide: 'debit' },

  // Expenses
  { code: '4000', name: 'Cost of goods sold', type: 'expense', subtype: 'cost_of_goods', normalSide: 'debit' },
  { code: '4010', name: 'Purchases', type: 'expense', subtype: 'cost_of_goods', normalSide: 'debit' },
  { code: '4100', name: 'Employee benefits', type: 'expense', subtype: 'operating_expense', normalSide: 'debit' },
  { code: '4200', name: 'Rent', type: 'expense', subtype: 'operating_expense', normalSide: 'debit' },
  { code: '4300', name: 'Office expenses', type: 'expense', subtype: 'operating_expense', normalSide: 'debit' },
  { code: '4400', name: 'Travel and conveyance', type: 'expense', subtype: 'operating_expense', normalSide: 'debit' },
  { code: '4500', name: 'Marketing and advertising', type: 'expense', subtype: 'operating_expense', normalSide: 'debit' },
  { code: '4600', name: 'Professional fees', type: 'expense', subtype: 'operating_expense', normalSide: 'debit' },
  { code: '4650', name: 'Bank charges', type: 'expense', subtype: 'operating_expense', normalSide: 'debit' },
  { code: '4700', name: 'Depreciation', type: 'expense', subtype: 'operating_expense', normalSide: 'debit' },
  { code: '4800', name: 'Interest expense', type: 'expense', subtype: 'other_expense', normalSide: 'debit' },
  {
    code: '4950',
    name: 'Foreign exchange loss',
    type: 'expense',
    subtype: 'other_expense',
    normalSide: 'debit',
    isSystemAccount: true,
    systemRole: 'realized_fx_loss',
  },
  {
    code: '4960',
    name: 'Rounding',
    type: 'expense',
    subtype: 'other_expense',
    normalSide: 'debit',
    isSystemAccount: true,
    systemRole: 'rounding',
  },
];
