/**
 * Curated catalog content for the WeldSuite App Store.
 *
 * This is the source of truth for human-written copy. The admin "Seed catalog"
 * button upserts every entry below into master.app_catalog.
 *
 * Codes here MUST match the codes already in use across the platform
 * (see apps/web/platform/lib/apps/app-registry.ts and the FALLBACK_CATALOG).
 */

export interface SeedAppEntry {
  code: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  path: string;
  overview: string;
  features: string[];
  howItWorks: { title: string; description: string }[];
  sortOrder: number;
  version: string;
  provider: string;
  verified: boolean;
  releasedAt: string; // ISO date
  websiteUrl: string | null;
  documentationUrl: string | null;
  contactUrl: string | null;
}

const HELP_BASE = 'https://help.weldsuite.com';
const SUPPORT_EMAIL = 'mailto:support@weldsuite.com';

export const APP_CATALOG_SEED: SeedAppEntry[] = [
  {
    code: 'weldcrm',
    name: 'WeldCRM',
    description: 'Win more deals with a CRM that lives where your team already works.',
    icon: 'Users',
    category: 'Sales & Marketing',
    path: '/weldcrm',
    overview:
      'WeldCRM is the customer system of record for your whole company — not just sales. Capture every lead from your website, inbox, helpdesk, and live chat into one timeline. Move deals through visual pipelines, log calls and meetings without leaving the page, and let WeldAgent draft the follow-up email while you read the transcript. Because WeldCRM shares contacts with WeldMail, WeldDesk, and WeldBooks, every conversation, ticket, and invoice is one click away from the contact card.',
    features: [
      'Unified contact, company, lead, and opportunity records with custom fields',
      'Drag-and-drop pipelines with weighted forecasting and stage automations',
      'Email, call, and meeting activity logged automatically through WeldMail and WeldMeet',
      'AI call intelligence — transcripts, summaries, action items, and sentiment per call',
      'Lead scoring, segmentation, and saved smart views',
      'Import wizard for HubSpot, Pipedrive, Salesforce, and CSV',
    ],
    howItWorks: [
      { title: 'Import contacts', description: 'Bring your contacts in from CSV, Google, or another CRM in under a minute.' },
      { title: 'Set up your pipeline', description: 'Define your sales stages and forecast targets per pipeline.' },
      { title: 'Connect your inbox', description: 'Link WeldMail so every email is auto-attached to the right contact.' },
      { title: 'Sell', description: 'Move deals through stages, log calls, and let WeldAgent draft follow-ups.' },
    ],
    sortOrder: 10,
    version: '2.4.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2024-02-12',
    websiteUrl: 'https://weldsuite.com/weldcrm',
    documentationUrl: `${HELP_BASE}/weldcrm`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'welddesk',
    name: 'WeldDesk',
    description: 'Customer support across email, chat, and the helpcenter — in one shared inbox.',
    icon: 'Headphones',
    category: 'Customer Support',
    path: '/welddesk',
    overview:
      "WeldDesk turns scattered customer messages into a single, accountable inbox. Email, the website chat widget, and the helpcenter all land as tickets your team can route, reply to, and resolve together. Internal notes, @-mentions, SLAs, and CSAT surveys are built in. WeldAgent can draft replies grounded in your knowledge base, suggest the right article to share, and auto-tag tickets so you always know what's hot.",
    features: [
      'Unified inbox for email, embedded chat widget, and helpcenter contact forms',
      'Round-robin and load-balanced assignment with skills-based routing',
      'SLA targets, business hours, and breach alerts',
      'Internal notes, @-mentions, and side conversations with other teams',
      'Customer Satisfaction surveys (CSAT) sent on resolution',
      'AI reply drafting grounded in your published help articles',
    ],
    howItWorks: [
      { title: 'Connect a channel', description: 'Forward your support@ inbox or drop the chat widget on your site.' },
      { title: 'Set up departments', description: 'Create departments with their own routing rules and signatures.' },
      { title: 'Define SLAs', description: 'Pick first-response and resolution targets per priority.' },
      { title: 'Publish articles', description: 'Write help articles so WeldAgent can draft accurate replies.' },
      { title: 'Reply', description: 'Triage, reply, resolve. CSAT goes out automatically.' },
    ],
    sortOrder: 20,
    version: '3.1.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2023-11-08',
    websiteUrl: 'https://weldsuite.com/welddesk',
    documentationUrl: `${HELP_BASE}/welddesk`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldmail',
    name: 'WeldMail',
    description: 'A team inbox that knows your customers, deals, and tickets.',
    icon: 'Mail',
    category: 'Communication',
    path: '/weldmail',
    overview:
      "WeldMail is a full email client that lives inside WeldSuite. Connect Gmail, Outlook, or any IMAP/SMTP mailbox and every message is automatically linked to the matching contact, deal, or ticket. Send with templates, schedule for later, and see when recipients open. Shared mailboxes work like a lightweight helpdesk — assign, snooze, and resolve threads as a team without juggling labels.",
    features: [
      'Gmail, Outlook, and IMAP/SMTP support with OAuth where available',
      'Auto-linking of every message to the matching contact, deal, or ticket',
      'Shared team mailboxes with assignment, snooze, and resolve states',
      'Reusable templates with merge fields and scheduled send',
      'Open and click tracking with per-link metrics',
      'Inline drafting from WeldAgent for replies, summaries, and translations',
    ],
    howItWorks: [
      { title: 'Connect a mailbox', description: 'Sign in with Google, Microsoft, or paste IMAP/SMTP credentials.' },
      { title: 'Add a signature', description: 'Build a per-account signature with your branding.' },
      { title: 'Save templates', description: 'Turn your most-sent replies into reusable templates with merge fields.' },
      { title: 'Send', description: 'Compose, schedule, or let WeldAgent draft the first version.' },
    ],
    sortOrder: 30,
    version: '2.0.1',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2024-04-02',
    websiteUrl: 'https://weldsuite.com/weldmail',
    documentationUrl: `${HELP_BASE}/weldmail`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldflow',
    name: 'WeldFlow',
    description: 'Project management for teams that ship — sprints, sheets, whiteboards, and docs.',
    icon: 'FolderKanban',
    category: 'Productivity',
    path: '/weldflow',
    overview:
      "WeldFlow is built for teams that don't want to choose between Jira, Notion, and a whiteboard. Plan in sprints, organize in projects, brainstorm on whiteboards, and document decisions in nested docs — all sharing the same task graph. Time tracking, workload, and goals roll up automatically into per-project and per-person dashboards.",
    features: [
      'Projects, sprints, and tasks with subtasks, dependencies, and custom fields',
      'List, board, calendar, Gantt, and timeline views per project',
      'Whiteboards for diagrams and planning, with live multi-cursor editing',
      'Sheets — spreadsheet view of any task list with formulas',
      'Built-in time tracking that rolls up to billable invoices in WeldBooks',
      'Goals and OKRs that link to tasks and update from progress automatically',
    ],
    howItWorks: [
      { title: 'Create a project', description: 'Pick a template (Scrum, Kanban, Gantt) or start from scratch.' },
      { title: 'Invite the team', description: 'Add members and set per-project roles.' },
      { title: 'Plan a sprint', description: 'Create a sprint, drag in tasks, set capacity, kick off.' },
      { title: 'Track', description: 'Log time, update status, watch goals progress in real time.' },
    ],
    sortOrder: 40,
    version: '4.0.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2023-09-19',
    websiteUrl: 'https://weldsuite.com/weldflow',
    documentationUrl: `${HELP_BASE}/weldflow`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldconnect',
    name: 'WeldConnect',
    description: 'Personal task manager — your daily plan, separate from team work.',
    icon: 'CheckSquare',
    category: 'Productivity',
    path: '/weldconnect',
    overview:
      "WeldConnect is the to-do list for your personal stuff that doesn't belong on a team board. Quick capture, natural-language due dates, recurring tasks, and a Today view that pulls in everything assigned to you across WeldFlow, WeldDesk, and WeldMail. It's the inbox for your work day.",
    features: [
      'Quick capture with natural-language dates ("call Sarah tomorrow 3pm")',
      'Today, Upcoming, and Someday views',
      'Recurring tasks with skip and reschedule logic',
      'Pulls in tasks, tickets, and emails assigned to you across WeldSuite',
      'Subtasks, priorities, tags, and reminders',
      'Drag tasks onto your calendar to time-block your day',
    ],
    howItWorks: [
      { title: 'Capture', description: 'Add tasks from anywhere with the global ⌘K capture.' },
      { title: 'Plan', description: 'Open Today and rank what matters this morning.' },
      { title: 'Time-block', description: 'Drag tasks onto your calendar to commit to when.' },
      { title: 'Done', description: 'Check off, repeat tomorrow.' },
    ],
    sortOrder: 50,
    version: '1.6.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2024-08-21',
    websiteUrl: 'https://weldsuite.com/weldconnect',
    documentationUrl: `${HELP_BASE}/weldconnect`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldhost',
    name: 'WeldHost',
    description: 'Domains, DNS, and email forwarding — buy a domain in 30 seconds.',
    icon: 'Globe',
    category: 'Infrastructure',
    path: '/weldhost',
    overview:
      "WeldHost handles the boring infrastructure side of running a business. Buy a domain, manage DNS records with sane defaults, set up email forwarding to your real inbox, and let WeldHost auto-issue and renew SSL. When you launch a website with WeldCommerce, WeldHost wires the DNS, certs, and CDN for you in one click.",
    features: [
      'Domain registration across .com, .nl, .eu, .io, and 200+ TLDs',
      'DNS management with templates for Google Workspace, Microsoft 365, and SPF/DKIM/DMARC',
      'Free SSL via Let\'s Encrypt — auto-issued and auto-renewed',
      'Email forwarding (catch-all and per-address) without a full mailbox',
      'One-click site connect for WeldCommerce stores and WeldSuite portals',
      'Domain transfer in/out with EPP-code workflow',
    ],
    howItWorks: [
      { title: 'Search', description: 'Type a domain and see availability + price across TLDs.' },
      { title: 'Register', description: 'Check out — WHOIS privacy is on by default.' },
      { title: 'Wire it up', description: 'Use a template to add Google/Microsoft DNS records, or point to a WeldSuite app.' },
      { title: 'Launch', description: 'SSL auto-issues. You\'re live.' },
    ],
    sortOrder: 60,
    version: '1.3.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2024-06-04',
    websiteUrl: 'https://weldsuite.com/weldhost',
    documentationUrl: `${HELP_BASE}/weldhost`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'welddrive',
    name: 'WeldDrive',
    description: 'Central file hub for everything you upload across WeldSuite.',
    icon: 'HardDrive',
    category: 'Productivity',
    path: '/welddrive',
    overview:
      'WeldDrive is the file system underneath WeldSuite. Every attachment you drop in a ticket, email, project, or invoice lands here automatically — versioned, searchable, and sharable with link permissions. Upload directly, drag entire folders, or sync a local folder via the desktop app. Files inherit access from the record they\'re attached to, so nothing is silently public.',
    features: [
      'Auto-collected from every WeldSuite app — no manual uploading required',
      'Folder structure, tags, and full-text search (including PDFs and Office docs)',
      'Versioning with restore-to-previous and side-by-side preview',
      'Public share links with expiry, password, and download limits',
      'In-line preview for images, PDFs, video, audio, and Office docs',
      'Per-file permissions inherited from the record it\'s attached to',
    ],
    howItWorks: [
      { title: 'Use WeldSuite', description: 'Files attached anywhere appear in WeldDrive automatically.' },
      { title: 'Organize', description: 'Move, tag, or pin the files you reference often.' },
      { title: 'Share', description: 'Generate a share link with the access controls you need.' },
      { title: 'Find', description: 'Search across content, not just filenames.' },
    ],
    sortOrder: 70,
    version: '1.2.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2024-09-30',
    websiteUrl: 'https://weldsuite.com/welddrive',
    documentationUrl: `${HELP_BASE}/welddrive`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldknow',
    name: 'WeldKnow',
    description: 'Workspace knowledge base and wiki — nested pages, rich text, and search.',
    icon: 'BookOpen',
    category: 'Productivity',
    path: '/weldknow',
    overview:
      'WeldKnow is your team\'s shared brain. Build a workspace wiki out of nested pages with a Notion-style block editor — document processes, onboarding guides, meeting notes, and internal handbooks. Organize pages into spaces, pin favorites, restore older versions, and find anything through global search.',
    features: [
      'Nested page tree organized into spaces (team-wide or private)',
      'Block-based rich-text editor with slash commands, images, and tables',
      'Version history with automatic snapshots and one-click restore',
      'Per-user favorites pinned to the top of the sidebar',
      'Trash with restore for accidentally deleted pages',
      'Pages surface in WeldSuite global search',
    ],
    howItWorks: [
      { title: 'Create a space', description: 'Group related knowledge — a team, a product, a process area.' },
      { title: 'Write pages', description: 'Use the block editor; nest pages to any depth.' },
      { title: 'Organize', description: 'Drag pages into place, add icons and covers, favorite what you use daily.' },
      { title: 'Find', description: 'Search titles and content from anywhere in WeldSuite.' },
    ],
    sortOrder: 75,
    version: '1.0.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2026-07-01',
    websiteUrl: 'https://weldsuite.com/weldknow',
    documentationUrl: `${HELP_BASE}/weldknow`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldchat',
    name: 'WeldChat',
    description: 'Internal team chat — channels, DMs, threads, and huddles.',
    icon: 'MessageCircle',
    category: 'Communication',
    path: '/weldchat',
    overview:
      "WeldChat is internal team chat that doesn't pull you into another tab. Channels for teams and projects, DMs for one-on-ones, threads to keep noise out of the main channel, and huddles for quick voice. Because WeldChat shares the WeldSuite identity layer, mentions, files, and tasks all link bidirectionally with your other apps — start a thread from a ticket, turn a message into a task, share a deal card inline.",
    features: [
      'Public and private channels per team or project',
      'Threads, reactions, pins, bookmarks, and saved messages',
      'Voice huddles with screen-share for ad-hoc syncs',
      'Inline previews for WeldCRM contacts, WeldDesk tickets, and WeldFlow tasks',
      'Searchable archive across every channel you can read',
      'Notifications you can actually tune — per channel, per keyword, per schedule',
    ],
    howItWorks: [
      { title: 'Create channels', description: 'Spin up a channel per team or project. Set who can post.' },
      { title: 'Invite', description: 'Add teammates. They get a DM thread automatically.' },
      { title: 'Talk', description: 'Drop links to tickets, deals, and tasks — they render as cards.' },
      { title: 'Tune notifications', description: 'Set per-channel quiet hours and keyword alerts.' },
    ],
    sortOrder: 80,
    version: '1.0.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2025-02-17',
    websiteUrl: 'https://weldsuite.com/weldchat',
    documentationUrl: `${HELP_BASE}/weldchat`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldcalendar',
    name: 'WeldCalendar',
    description: 'A calendar that knows your meetings, deadlines, and time-blocked work.',
    icon: 'CalendarDays',
    category: 'Productivity',
    path: '/weldcalendar',
    overview:
      "WeldCalendar pulls your Google or Microsoft calendar into WeldSuite and lays your tasks, deadlines, and project milestones on top. Time-block work from WeldConnect by dragging it onto a slot. See your team's availability without setting up a separate scheduling tool. Built-in booking pages let prospects pick a time without back-and-forth email.",
    features: [
      'Two-way sync with Google Calendar and Microsoft 365',
      'Drag tasks from WeldConnect onto your calendar to time-block them',
      'Team view with per-person availability and meeting density',
      'Public booking pages with round-robin and per-meeting-type rules',
      'Auto-create WeldMeet video links on accepted invites',
      'Project deadlines and sprint dates overlaid as ghost events',
    ],
    howItWorks: [
      { title: 'Connect', description: 'Sign in with Google or Microsoft.' },
      { title: 'Set hours', description: 'Mark your working hours and quiet times.' },
      { title: 'Publish booking', description: 'Create a booking page (sales call, intro chat, demo) and share the link.' },
      { title: 'Plan', description: 'Drag tasks onto open slots to commit to your day.' },
    ],
    sortOrder: 90,
    version: '1.4.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2024-07-18',
    websiteUrl: 'https://weldsuite.com/weldcalendar',
    documentationUrl: `${HELP_BASE}/weldcalendar`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldmeet',
    name: 'WeldMeet',
    description: 'Video meetings with AI notes — recorded, transcribed, summarized.',
    icon: 'Video',
    category: 'Communication',
    path: '/weldmeet',
    overview:
      "WeldMeet is video conferencing built for sales and support. Click a contact, click Meet — the link is in their inbox. Every call records, transcribes, and summarizes automatically; the summary, action items, and full transcript land on the contact card in WeldCRM (or the ticket in WeldDesk). The Meeting Bot can join your Google Meet, Zoom, or Teams calls too, so you don't have to migrate.",
    features: [
      'HD video and screen share with up to 100 participants',
      'AI transcription and summary in 30+ languages',
      'Automatic action-item extraction with assignees',
      'Recording stored in WeldDrive, transcript searchable in WeldCRM',
      'Meeting Bot for Google Meet, Zoom, and Microsoft Teams',
      'Booking pages from WeldCalendar create WeldMeet links automatically',
    ],
    howItWorks: [
      { title: 'Start a meeting', description: 'Click Meet on any contact — the link goes in their inbox.' },
      { title: 'Talk', description: 'Recording and live transcript run in the background.' },
      { title: 'Review', description: 'After the call, summary + action items appear on the contact.' },
      { title: 'Follow up', description: 'WeldAgent drafts the follow-up email from the transcript.' },
    ],
    sortOrder: 100,
    version: '2.2.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2024-05-14',
    websiteUrl: 'https://weldsuite.com/weldmeet',
    documentationUrl: `${HELP_BASE}/weldmeet`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldcommerce',
    name: 'WeldCommerce',
    description: 'Online store, website builder, and order management — with real inventory.',
    icon: 'ShoppingCart',
    category: 'Sales & Marketing',
    path: '/weldcommerce',
    overview:
      "WeldCommerce is an end-to-end commerce stack. Build your storefront with the visual website builder, manage products with variants and bundles, take payment with Stripe / Mollie / PayPal, and watch orders flow into the same inventory and shipping layer used by WeldWMS and WeldParcel. No webhooks, no syncing — orders, stock, and shipments all share one database. Sync to Shopify or WooCommerce if you'd rather keep your existing storefront.",
    features: [
      'Drag-and-drop website builder with sections, blocks, and reusable templates',
      'Products with variants, bundles, digital goods, and per-warehouse stock',
      'Multi-currency pricing with automatic conversion',
      'Payments via Stripe, Mollie, PayPal, Adyen, and bank transfer',
      'Discount engine: codes, BOGO, tiered, automatic cart rules',
      'Two-way sync with Shopify and WooCommerce for migrations or mirroring',
    ],
    howItWorks: [
      { title: 'Pick a template', description: 'Choose a starter template or import your existing brand.' },
      { title: 'Add products', description: 'Bulk-import via CSV or sync from Shopify/WooCommerce.' },
      { title: 'Configure checkout', description: 'Connect Stripe/Mollie and pick shipping methods.' },
      { title: 'Launch', description: 'Connect a domain via WeldHost and you\'re live.' },
    ],
    sortOrder: 110,
    version: '3.0.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2023-08-22',
    websiteUrl: 'https://weldsuite.com/weldcommerce',
    documentationUrl: `${HELP_BASE}/weldcommerce`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldbooks',
    name: 'WeldBooks',
    description: 'Multi-entity accounting — invoices, bills, banking, VAT returns.',
    icon: 'Calculator',
    category: 'Finance',
    path: '/weldbooks',
    overview:
      'WeldBooks is full double-entry accounting built into WeldSuite. Run multiple legal entities (BV, GmbH, Ltd, Inc, sole prop) from the same workspace, each with its own chart of accounts, tax rates, invoice numbering, and filing setup. Multi-currency works end-to-end with historical ECB rates and automatic FX gain/loss postings. Launches with first-class Netherlands support — quarterly BTW with SBR/XBRL filing to Digipoort — and the jurisdiction adapter pattern lets us add other countries without schema changes.',
    features: [
      'Multiple legal entities per workspace, each fully scoped',
      'Customer invoices and supplier bills with per-entity numbering',
      'Chart of accounts seeded per jurisdiction (Dutch RGS out of the box)',
      'Bank import via MT940 / CAMT.053 / CSV with auto-reconciliation rules',
      'Multi-currency with historical ECB rates and realized FX gain/loss postings',
      'Dutch BTW: quarterly rubrieken calculation and SBR/XBRL filing to Digipoort',
      'Reports: P&L, balance sheet, trial balance, aged AR/AP, cash flow',
      'Recurring invoices, credit notes, payment reminders, approval workflows',
    ],
    howItWorks: [
      { title: 'Create entity', description: 'Add your legal entity — jurisdiction adapter seeds COA + tax rates.' },
      { title: 'Connect bank', description: 'Import a statement; transactions land ready for reconciliation.' },
      { title: 'Invoice', description: 'Send your first invoice — numbering, tax, and PDF render per entity.' },
      { title: 'Reconcile', description: 'Match payments to invoices with one-click suggestions.' },
      { title: 'File', description: 'At period end, generate and file your VAT return directly from the app.' },
    ],
    sortOrder: 120,
    version: '1.0.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2026-01-15',
    websiteUrl: 'https://weldsuite.com/weldbooks',
    documentationUrl: `${HELP_BASE}/weldbooks`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'weldcall',
    name: 'WeldCall',
    description: 'Business phone system — inbound, outbound, IVR, and CRM-linked call history.',
    icon: 'Phone',
    category: 'Communication',
    path: '/weldcall',
    overview:
      "WeldCall is cloud telephony built into WeldSuite. Provision local and international numbers, take calls from your browser or mobile, and route inbound traffic through an IVR with business hours and skills-based queues. Every call automatically logs against the matching contact, lead, or deal in WeldCRM with a recording, voicemail-to-text transcript, and AI summary. Click-to-call works from any record across the suite, so picking up the phone never means losing context.",
    features: [
      'Inbound and outbound calling from web, desktop, and mobile apps',
      'Number provisioning and porting across 50+ countries',
      'Visual IVR builder with menus, business hours, and conditional routing',
      'Call queues with round-robin, skills-based, and overflow assignment',
      'Automatic logging to WeldCRM contacts, leads, deals, and WeldDesk tickets',
      'Call recording with retention policies and consent prompts',
      'Voicemail-to-text and AI call summaries with action items',
      'Click-to-call from any contact, ticket, or deal in WeldSuite',
    ],
    howItWorks: [
      { title: 'Pick a number', description: 'Provision a local or toll-free number — or port your existing one.' },
      { title: 'Build your IVR', description: 'Drag together your menu, business hours, and overflow rules.' },
      { title: 'Set up queues', description: 'Add agents to queues with skills, priorities, and wrap-up codes.' },
      { title: 'Connect WeldCRM', description: 'Calls auto-log to the matching contact or deal — no manual logging.' },
      { title: 'Go live', description: 'Take calls in the browser. Recordings, transcripts, and summaries appear on the contact.' },
    ],
    sortOrder: 130,
    version: '1.0.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2026-05-04',
    websiteUrl: 'https://weldsuite.com/weldcall',
    documentationUrl: `${HELP_BASE}/weldcall`,
    contactUrl: SUPPORT_EMAIL,
  },
  {
    code: 'social',
    name: 'WeldSocial',
    description: 'Plan, schedule, and publish to every social channel from one calendar.',
    icon: 'Share2',
    category: 'Sales & Marketing',
    path: '/social',
    overview:
      'WeldSocial is your team\'s social media command center. Connect Instagram, X, LinkedIn, Facebook, and TikTok through a single unified provider, then compose once and publish everywhere. Queue posts on a visual content calendar, route them through an approval workflow, group them into campaigns, and track engagement — all without leaving WeldSuite. Publishing, scheduling, and analytics are powered by PostPeer, so there are no per-network OAuth apps to maintain.',
    features: [
      'Connect all major networks through one unified provider (PostPeer)',
      'Multi-channel composer with media, scheduling, and per-network previews',
      'Visual content calendar and publishing queue with drag-to-reschedule',
      'Approval workflows, campaigns, and team roles',
      'Engagement analytics — impressions, reach, and interactions per post',
      'Drafts, labels, and best-time-to-post suggestions',
    ],
    howItWorks: [
      { title: 'Connect your channels', description: 'Authorize each network once through the unified provider — no app setup.' },
      { title: 'Compose a post', description: 'Write once, attach media, and pick the channels to publish to.' },
      { title: 'Schedule or publish', description: 'Drop it on the calendar or publish immediately; WeldSocial handles delivery.' },
      { title: 'Measure', description: 'Sync engagement metrics back into WeldSocial to see what works.' },
    ],
    sortOrder: 140,
    version: '1.0.0',
    provider: 'WeldSuite',
    verified: true,
    releasedAt: '2026-06-30',
    websiteUrl: 'https://weldsuite.com/social',
    documentationUrl: `${HELP_BASE}/social`,
    contactUrl: SUPPORT_EMAIL,
  },
];
