import { getLocale } from '@weldsuite/i18n';

/**
 * Copy for the partner (reseller) screens, en + nl. It lives with the console
 * rather than in the `admin` namespace of @weldsuite/i18n only because that
 * package was owned by another workstream while this was built; move it there
 * when convenient (same shape: nested objects, `{placeholder}` filled by
 * `fill()` from ./i18n).
 */

const en = {
  nav: {
    area: 'Partners',
    group: 'Resellers',
    list: 'All partners',
    new: 'New partner',
    jumpTo: 'Partners',
  },
  common: {
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    working: 'Working…',
    remove: 'Remove',
    none: 'None',
    yes: 'Yes',
    no: 'No',
    optional: 'Optional',
    unlimited: 'Unlimited',
    readOnlyNote: 'Your account has read-only access.',
    loadFailed: 'The partner data could not be loaded.',
    notConfigured: 'The billing worker is not configured for this console, so partners cannot be loaded or changed.',
    backToPartners: 'All partners',
    reason: 'Reason',
    reasonHint: 'Saved in the activity log.',
    month: 'Month (YYYY-MM)',
    since: 'since {date}',
    perMonth: '/ month',
    credits: 'credits',
    seats: 'seats',
    days: '{count} days',
  },
  status: {
    active: 'Active',
    past_due: 'Past due',
    suspended: 'Suspended',
  },
  stage: {
    current: 'Current',
    past_due: 'Past due',
    final_warning: 'Final warning',
    suspended: 'Workspaces read-only',
  },
  licenceStatus: {
    active: 'Active',
    suspended: 'Suspended',
    ended: 'Ended',
  },
  statementStatus: {
    preview: 'Preview',
    draft: 'Draft',
    final: 'Final',
    invoiced: 'Invoiced',
    paid: 'Paid',
    void: 'Void',
  },
  roles: {
    owner: 'Owner',
    admin: 'Admin',
    billing: 'Billing',
    viewer: 'Viewer',
  },
  list: {
    title: 'Partners',
    description: 'Resellers that license workspaces for their own customers and pay WeldSuite monthly.',
    newPartner: 'New partner',
    empty: 'No partners yet.',
    columns: {
      partner: 'Partner',
      status: 'Status',
      billingEmail: 'Billing email',
      workspaces: 'Workspaces',
      territories: 'Territories',
      overdue: 'Overdue',
      created: 'Created',
    },
    territoriesCount: '{count} countries',
    noTerritories: 'None',
    overdueCount: '{count} overdue',
    notOverdue: '—',
  },
  new: {
    title: 'New partner',
    description:
      'Creates the partner and its Stripe customer, records the first contract and territories, and invites the owner to the partner portal.',
    profile: 'Company',
    owner: 'Portal owner',
    ownerEmail: 'Owner email',
    ownerHint: 'Invited as the partner\'s first owner. They open the portal in the platform with this email.',
    contract: 'First contract',
    territories: 'Territories',
    submit: 'Create partner',
    created: 'Partner created.',
    territoryConflict: 'These countries already belong to another partner: {countries}. Remove them and try again.',
  },
  detail: {
    tabs: {
      profile: 'Profile',
      contract: 'Contract',
      territories: 'Territories',
      members: 'Members',
      workspaces: 'Workspaces',
      statements: 'Statements',
      payment: 'Payment status',
    },
    stripeCustomer: 'Stripe customer',
    noStripeCustomer: 'Not created',
  },
  profile: {
    title: 'Company profile',
    hint: 'The support details and logo are shown to the partner\'s customers (managed-by screen, territory screen).',
    name: 'Name',
    legalName: 'Legal name',
    country: 'Country (ISO-2)',
    taxId: 'Tax ID',
    billingEmail: 'Billing email',
    billingEmailHint: 'WeldSuite statements and payment reminders go here.',
    supportEmail: 'Support email',
    supportUrl: 'Support URL',
    websiteUrl: 'Website URL',
    logoUrl: 'Logo URL',
    saved: 'Profile saved.',
    noChanges: 'Nothing changed.',
  },
  contract: {
    title: 'Contract',
    current: 'In force',
    history: 'History',
    newTitle: 'New contract',
    newHint:
      'Contracts are never edited. A new one takes effect on the date below (default: now) and closes the previous one on that date. Statements follow the licence history, so changes are prorated by day.',
    effectiveFrom: 'Effective from',
    effectiveFromHint: 'YYYY-MM-DD, UTC. Blank means now.',
    revenueShare: 'WeldSuite share (%)',
    revenueShareHint: 'Of what the partner charges its customer. 75 means the partner keeps 25%.',
    baseMinimum: 'Base minimum per workspace (USD / month)',
    includedCredits: 'Credits included in the minimum',
    creditFloorPrice: 'Floor price per extra licensed credit (USD)',
    creditFloorPriceHint: 'Charged per licensed credit above the included amount, up to 6 decimals.',
    extraCreditPrice: 'Price per granted extra credit (USD)',
    featurePlans: 'Feature plans a licence may use',
    featurePlansHint: 'Empty means every paid plan.',
    paymentTerms: 'Payment terms (days)',
    pastDueAfter: 'Past due after (days)',
    readOnlyAfter: 'Workspaces read-only after (days)',
    notes: 'Notes',
    submit: 'Create contract',
    created: 'Contract created.',
    empty: 'No contract.',
    columns: {
      from: 'From',
      to: 'To',
      share: 'Share',
      minimum: 'Minimum',
      credits: 'Included credits',
      creditFloor: 'Credit floor',
      terms: 'Terms',
    },
    open: 'Open',
    termsSummary: 'Net {terms}, past due {pastDue}, read-only {readOnly}',
  },
  territories: {
    title: 'Territories',
    description:
      'A country can belong to only one partner. People creating a workspace from these countries are pointed to the partner, and direct checkout is closed for them. Existing direct workspaces stay direct.',
    pick: 'Countries',
    placeholder: 'Select countries…',
    search: 'Search countries…',
    empty: 'No countries found.',
    presetsTitle: 'Add a region',
    presets: {
      northAmerica: 'North America',
      centralAmerica: 'Central America',
      caribbean: 'Caribbean',
      southAmerica: 'South America',
    },
    clear: 'Clear all',
    count: '{count} selected',
    saved: 'Territories saved.',
    conflictTitle: 'Territory conflict',
    conflict: 'These countries already belong to another partner and were not saved: {countries}.',
    unsaved: 'Unsaved changes',
    willAdd: 'Adds {countries}',
    willRemove: 'Removes {countries}',
  },
  members: {
    title: 'Portal members',
    description: 'People who can sign in to the partner portal. Owners manage the team; admins manage workspaces and licences.',
    email: 'Email',
    role: 'Role',
    status: 'Status',
    accepted: 'Joined',
    invited: 'Invited',
    invite: 'Invite member',
    inviteSubmit: 'Send invite',
    invitedToast: 'Invite sent.',
    removed: 'Member removed.',
    removeTitle: 'Remove member',
    removeConfirm: 'Remove {email} from {partner}? They lose portal access immediately.',
    empty: 'No members yet.',
  },
  workspaces: {
    title: 'Managed workspaces',
    description: 'Workspaces billed to this partner. A licence decides which apps, credits and seats a workspace gets.',
    empty: 'No workspaces attached.',
    columns: {
      workspace: 'Workspace',
      status: 'Licence',
      apps: 'Apps',
      credits: 'Credits / month',
      seats: 'Seats',
      price: 'Customer price',
      actions: 'Actions',
    },
    noLicence: 'No licence',
    allApps: 'All apps',
    flat: '{amount} flat',
    perSeat: '{amount} per seat',
    perSeatMin: '{amount} per seat (min {min})',
    attach: 'Attach workspace',
    attachTitle: 'Attach an existing workspace',
    attachHint:
      'Moves a direct workspace under this partner. Its own Stripe subscription is cancelled and WeldSuite stops billing it directly; the partner pays instead. Its apps, credits and seat cap are set from the licence.',
    workspaceId: 'Workspace ID',
    workspaceIdHint: 'The workspace id (not the Clerk org id). Search to fill it in.',
    findWorkspace: 'Find by name or slug',
    cancelDirect: 'Direct subscription',
    cancelNow: 'Cancel now (with proration)',
    cancelPeriodEnd: 'Cancel at period end',
    attachSubmit: 'Attach',
    attached: 'Workspace attached.',
    detach: 'Detach',
    detachTitle: 'Detach {name}',
    detachHint:
      'Ends the licence and returns the workspace to direct billing: it falls back to the normal paywall with the usual grace window. Its data is kept.',
    detachSubmit: 'Detach workspace',
    detached: 'Workspace detached.',
    editLicence: 'Edit licence',
    editTitle: 'Licence for {name}',
    editHint: 'An admin override. It is recorded in the licence history and the activity log, and applies to the workspace immediately.',
    editSubmit: 'Save licence',
    licenceSaved: 'Licence saved.',
    licence: {
      apps: 'Apps',
      appsPlaceholder: 'Select apps…',
      appsSearch: 'Search apps…',
      appsEmpty: 'No apps found.',
      credits: 'Credits per month',
      rollover: 'Rollover cap',
      rolloverHint: 'Unused credits carried into next month, up to this amount. 0 resets to the allowance.',
      maxSeats: 'Seat cap',
      maxSeatsHint: 'Blank means unlimited.',
      featurePlan: 'Feature plan',
      featurePlanNone: 'None',
      storage: 'Storage (GB)',
      storageHint: 'Recorded only; not enforced yet.',
      pricing: 'Customer price',
      pricingModel: 'Model',
      flatModel: 'Flat per workspace',
      perSeatModel: 'Per seat',
      amount: 'Amount (USD / month)',
      minSeats: 'Minimum billed seats',
    },
  },
  statements: {
    title: 'Statements',
    description:
      'What this partner owes WeldSuite, one per month: max(resale × WeldSuite share, floor) per workspace, plus extra credits granted. The monthly run invoices on the 1st.',
    empty: 'No statements yet.',
    columns: {
      period: 'Period',
      status: 'Status',
      resale: 'Resale',
      due: 'WeldSuite bills',
      margin: 'Partner keeps',
      dueAt: 'Due',
      actions: 'Actions',
    },
    previewTitle: 'Preview or run a month',
    previewHint: 'Preview calculates the month live and saves nothing. Run rebuilds the statement and invoices it.',
    preview: 'Preview',
    run: 'Run',
    runTitle: 'Run statement for {period}',
    runHint:
      'Rebuilds the statement for this month and sends the Stripe invoice to the partner. A statement that is already invoiced, paid or void cannot be rebuilt; void it first.',
    runSubmit: 'Run and invoice',
    ran: 'Statement run.',
    view: 'View',
    void: 'Void',
    voidTitle: 'Void statement for {period}',
    voidHint: 'Marks the statement void and voids its Stripe invoice. The partner is no longer asked to pay it.',
    voidSubmit: 'Void statement',
    voided: 'Statement voided.',
    invoice: 'Invoice',
    pdf: 'PDF',
    detailTitle: 'Statement {period}',
    totals: { resale: 'Customer prices', due: 'WeldSuite bills', margin: 'Partner keeps' },
    lines: {
      workspace: 'Workspace',
      days: 'Days',
      seats: 'Seats',
      resale: 'Resale',
      share: 'Share',
      floor: 'Floor',
      creditFloor: 'Credit floor',
      extraCredits: 'Extra credits',
      due: 'Due',
      margin: 'Margin',
      empty: 'No lines.',
    },
    paidAt: 'Paid {date}',
    dueAt: 'Due {date}',
    close: 'Close',
    loadFailed: 'The statement could not be loaded.',
  },
  payment: {
    title: 'Payment status',
    description:
      'An unpaid invoice turns the partner past due and, later, makes every one of its workspaces read-only. Nothing is deleted. Paying lifts it.',
    current: 'Current status',
    changedAt: 'Changed {date}',
    sweepStage: 'Dunning stage',
    overdueInvoices: 'Overdue invoices',
    noneOverdue: 'Nothing is overdue.',
    daysOverdue: '{count} days overdue',
    due: 'due {date}',
    clock: 'Dunning clock',
    clockRunning: 'Running',
    clockPaused: 'Paused until {date}',
    clockHint: 'Pausing holds the partner at current even when an invoice is overdue, for example during a payment plan.',
    thresholds: 'Past due after {pastDue} days, workspaces read-only after {readOnly} days.',
    pause: 'Pause the clock',
    pauseTitle: 'Pause the dunning clock',
    pauseHint: 'The clock does not advance until the end of the chosen day.',
    pauseFor: 'Pause for',
    pauseDays: '{count} days',
    pauseSubmit: 'Pause clock',
    paused: 'Clock paused.',
    resume: 'Resume the clock',
    resumeTitle: 'Resume the dunning clock',
    resumeHint: 'Clears the pause. The next daily sweep puts the partner in the stage its overdue invoices call for.',
    resumeSubmit: 'Resume clock',
    resumed: 'Clock resumed.',
    setStatus: 'Set status',
    setTitle: 'Set payment status',
    setHint:
      'A manual override. Suspending makes every workspace of this partner read-only at once; setting it back to active lifts that. The next sweep can change it again if an invoice is still overdue, so pause the clock as well when needed.',
    newStatus: 'Status',
    setSubmit: 'Set status',
    statusSet: 'Status updated.',
  },
};

export type PartnersCopy = typeof en;

const nl: PartnersCopy = {
  nav: {
    area: 'Partners',
    group: 'Resellers',
    list: 'Alle partners',
    new: 'Nieuwe partner',
    jumpTo: 'Partners',
  },
  common: {
    save: 'Opslaan',
    saving: 'Opslaan…',
    cancel: 'Annuleren',
    working: 'Bezig…',
    remove: 'Verwijderen',
    none: 'Geen',
    yes: 'Ja',
    no: 'Nee',
    optional: 'Optioneel',
    unlimited: 'Onbeperkt',
    readOnlyNote: 'Je account heeft alleen leestoegang.',
    loadFailed: 'De partnergegevens konden niet worden geladen.',
    notConfigured: 'De billing worker is niet ingesteld voor deze console, dus partners kunnen niet worden geladen of gewijzigd.',
    backToPartners: 'Alle partners',
    reason: 'Reden',
    reasonHint: 'Wordt vastgelegd in het activiteitenlogboek.',
    month: 'Maand (JJJJ-MM)',
    since: 'sinds {date}',
    perMonth: '/ maand',
    credits: 'credits',
    seats: 'gebruikers',
    days: '{count} dagen',
  },
  status: {
    active: 'Actief',
    past_due: 'Achterstallig',
    suspended: 'Opgeschort',
  },
  stage: {
    current: 'Op orde',
    past_due: 'Achterstallig',
    final_warning: 'Laatste waarschuwing',
    suspended: 'Workspaces alleen-lezen',
  },
  licenceStatus: {
    active: 'Actief',
    suspended: 'Opgeschort',
    ended: 'Beëindigd',
  },
  statementStatus: {
    preview: 'Voorbeeld',
    draft: 'Concept',
    final: 'Definitief',
    invoiced: 'Gefactureerd',
    paid: 'Betaald',
    void: 'Vervallen',
  },
  roles: {
    owner: 'Eigenaar',
    admin: 'Beheerder',
    billing: 'Facturatie',
    viewer: 'Lezer',
  },
  list: {
    title: 'Partners',
    description: 'Resellers die workspaces voor hun eigen klanten in licentie geven en WeldSuite maandelijks betalen.',
    newPartner: 'Nieuwe partner',
    empty: 'Nog geen partners.',
    columns: {
      partner: 'Partner',
      status: 'Status',
      billingEmail: 'Facturatie-e-mail',
      workspaces: 'Workspaces',
      territories: 'Gebieden',
      overdue: 'Achterstallig',
      created: 'Aangemaakt',
    },
    territoriesCount: '{count} landen',
    noTerritories: 'Geen',
    overdueCount: '{count} achterstallig',
    notOverdue: '—',
  },
  new: {
    title: 'Nieuwe partner',
    description:
      'Maakt de partner en zijn Stripe-klant aan, legt het eerste contract en de gebieden vast en nodigt de eigenaar uit voor het partnerportaal.',
    profile: 'Bedrijf',
    owner: 'Portaaleigenaar',
    ownerEmail: 'E-mail van de eigenaar',
    ownerHint: 'Wordt uitgenodigd als eerste eigenaar van de partner. Hij of zij opent het portaal in het platform met dit e-mailadres.',
    contract: 'Eerste contract',
    territories: 'Gebieden',
    submit: 'Partner aanmaken',
    created: 'Partner aangemaakt.',
    territoryConflict: 'Deze landen horen al bij een andere partner: {countries}. Verwijder ze en probeer opnieuw.',
  },
  detail: {
    tabs: {
      profile: 'Profiel',
      contract: 'Contract',
      territories: 'Gebieden',
      members: 'Leden',
      workspaces: 'Workspaces',
      statements: 'Afrekeningen',
      payment: 'Betaalstatus',
    },
    stripeCustomer: 'Stripe-klant',
    noStripeCustomer: 'Niet aangemaakt',
  },
  profile: {
    title: 'Bedrijfsprofiel',
    hint: 'De supportgegevens en het logo worden getoond aan de klanten van de partner (scherm "beheerd door", gebiedsscherm).',
    name: 'Naam',
    legalName: 'Juridische naam',
    country: 'Land (ISO-2)',
    taxId: 'Btw-nummer',
    billingEmail: 'Facturatie-e-mail',
    billingEmailHint: 'Afrekeningen en betalingsherinneringen van WeldSuite gaan hierheen.',
    supportEmail: 'Support-e-mail',
    supportUrl: 'Support-URL',
    websiteUrl: 'Website-URL',
    logoUrl: 'Logo-URL',
    saved: 'Profiel opgeslagen.',
    noChanges: 'Niets gewijzigd.',
  },
  contract: {
    title: 'Contract',
    current: 'Van kracht',
    history: 'Geschiedenis',
    newTitle: 'Nieuw contract',
    newHint:
      'Contracten worden nooit aangepast. Een nieuw contract gaat in op de datum hieronder (standaard: nu) en sluit het vorige op die datum. Afrekeningen volgen de licentiegeschiedenis, dus wijzigingen worden per dag verrekend.',
    effectiveFrom: 'Ingangsdatum',
    effectiveFromHint: 'JJJJ-MM-DD, UTC. Leeg betekent nu.',
    revenueShare: 'Aandeel WeldSuite (%)',
    revenueShareHint: 'Van wat de partner zijn klant rekent. 75 betekent dat de partner 25% houdt.',
    baseMinimum: 'Basisminimum per workspace (USD / maand)',
    includedCredits: 'Credits inbegrepen in het minimum',
    creditFloorPrice: 'Minimumprijs per extra gelicentieerde credit (USD)',
    creditFloorPriceHint: 'Per gelicentieerde credit boven het inbegrepen aantal, tot 6 decimalen.',
    extraCreditPrice: 'Prijs per toegekende extra credit (USD)',
    featurePlans: 'Featureplannen die een licentie mag gebruiken',
    featurePlansHint: 'Leeg betekent elk betaald plan.',
    paymentTerms: 'Betalingstermijn (dagen)',
    pastDueAfter: 'Achterstallig na (dagen)',
    readOnlyAfter: 'Workspaces alleen-lezen na (dagen)',
    notes: 'Notities',
    submit: 'Contract aanmaken',
    created: 'Contract aangemaakt.',
    empty: 'Geen contract.',
    columns: {
      from: 'Van',
      to: 'Tot',
      share: 'Aandeel',
      minimum: 'Minimum',
      credits: 'Inbegrepen credits',
      creditFloor: 'Credit-minimum',
      terms: 'Voorwaarden',
    },
    open: 'Open',
    termsSummary: 'Netto {terms}, achterstallig {pastDue}, alleen-lezen {readOnly}',
  },
  territories: {
    title: 'Gebieden',
    description:
      'Een land kan maar bij één partner horen. Mensen die vanuit deze landen een workspace maken, worden naar de partner verwezen en rechtstreeks afrekenen is voor hen gesloten. Bestaande directe workspaces blijven direct.',
    pick: 'Landen',
    placeholder: 'Selecteer landen…',
    search: 'Zoek landen…',
    empty: 'Geen landen gevonden.',
    presetsTitle: 'Voeg een regio toe',
    presets: {
      northAmerica: 'Noord-Amerika',
      centralAmerica: 'Midden-Amerika',
      caribbean: 'Caribisch gebied',
      southAmerica: 'Zuid-Amerika',
    },
    clear: 'Alles wissen',
    count: '{count} geselecteerd',
    saved: 'Gebieden opgeslagen.',
    conflictTitle: 'Gebiedsconflict',
    conflict: 'Deze landen horen al bij een andere partner en zijn niet opgeslagen: {countries}.',
    unsaved: 'Niet-opgeslagen wijzigingen',
    willAdd: 'Voegt toe: {countries}',
    willRemove: 'Verwijdert: {countries}',
  },
  members: {
    title: 'Portaalleden',
    description: 'Mensen die kunnen inloggen op het partnerportaal. Eigenaren beheren het team; beheerders beheren workspaces en licenties.',
    email: 'E-mail',
    role: 'Rol',
    status: 'Status',
    accepted: 'Toegetreden',
    invited: 'Uitgenodigd',
    invite: 'Lid uitnodigen',
    inviteSubmit: 'Uitnodiging versturen',
    invitedToast: 'Uitnodiging verstuurd.',
    removed: 'Lid verwijderd.',
    removeTitle: 'Lid verwijderen',
    removeConfirm: '{email} verwijderen uit {partner}? De toegang tot het portaal vervalt direct.',
    empty: 'Nog geen leden.',
  },
  workspaces: {
    title: 'Beheerde workspaces',
    description: 'Workspaces die aan deze partner worden gefactureerd. Een licentie bepaalt welke apps, credits en gebruikers een workspace krijgt.',
    empty: 'Geen workspaces gekoppeld.',
    columns: {
      workspace: 'Workspace',
      status: 'Licentie',
      apps: 'Apps',
      credits: 'Credits / maand',
      seats: 'Gebruikers',
      price: 'Klantprijs',
      actions: 'Acties',
    },
    noLicence: 'Geen licentie',
    allApps: 'Alle apps',
    flat: '{amount} vast',
    perSeat: '{amount} per gebruiker',
    perSeatMin: '{amount} per gebruiker (min. {min})',
    attach: 'Workspace koppelen',
    attachTitle: 'Een bestaande workspace koppelen',
    attachHint:
      'Verplaatst een directe workspace naar deze partner. Het eigen Stripe-abonnement wordt opgezegd en WeldSuite factureert de workspace niet meer rechtstreeks; de partner betaalt. Apps, credits en gebruikerslimiet volgen de licentie.',
    workspaceId: 'Workspace-ID',
    workspaceIdHint: 'Het workspace-id (niet het Clerk-org-id). Zoek om het in te vullen.',
    findWorkspace: 'Zoek op naam of slug',
    cancelDirect: 'Direct abonnement',
    cancelNow: 'Nu opzeggen (met verrekening)',
    cancelPeriodEnd: 'Opzeggen aan het einde van de periode',
    attachSubmit: 'Koppelen',
    attached: 'Workspace gekoppeld.',
    detach: 'Ontkoppelen',
    detachTitle: '{name} ontkoppelen',
    detachHint:
      'Beëindigt de licentie en zet de workspace terug op rechtstreekse facturatie: hij valt terug op de gewone betaalmuur met de gebruikelijke respijtperiode. De gegevens blijven bewaard.',
    detachSubmit: 'Workspace ontkoppelen',
    detached: 'Workspace ontkoppeld.',
    editLicence: 'Licentie bewerken',
    editTitle: 'Licentie van {name}',
    editHint: 'Een beheerdersoverschrijving. Ze wordt vastgelegd in de licentiegeschiedenis en het activiteitenlogboek en geldt direct voor de workspace.',
    editSubmit: 'Licentie opslaan',
    licenceSaved: 'Licentie opgeslagen.',
    licence: {
      apps: 'Apps',
      appsPlaceholder: 'Selecteer apps…',
      appsSearch: 'Zoek apps…',
      appsEmpty: 'Geen apps gevonden.',
      credits: 'Credits per maand',
      rollover: 'Doorrolplafond',
      rolloverHint: 'Ongebruikte credits die naar volgende maand doorschuiven, tot dit aantal. 0 reset naar het tegoed.',
      maxSeats: 'Gebruikerslimiet',
      maxSeatsHint: 'Leeg betekent onbeperkt.',
      featurePlan: 'Featureplan',
      featurePlanNone: 'Geen',
      storage: 'Opslag (GB)',
      storageHint: 'Wordt alleen vastgelegd; nog niet afgedwongen.',
      pricing: 'Klantprijs',
      pricingModel: 'Model',
      flatModel: 'Vast per workspace',
      perSeatModel: 'Per gebruiker',
      amount: 'Bedrag (USD / maand)',
      minSeats: 'Minimaal gefactureerde gebruikers',
    },
  },
  statements: {
    title: 'Afrekeningen',
    description:
      'Wat deze partner WeldSuite verschuldigd is, één per maand: max(verkoop × aandeel WeldSuite, minimum) per workspace, plus toegekende extra credits. De maandelijkse run factureert op de 1e.',
    empty: 'Nog geen afrekeningen.',
    columns: {
      period: 'Periode',
      status: 'Status',
      resale: 'Verkoop',
      due: 'WeldSuite factureert',
      margin: 'Partner houdt',
      dueAt: 'Vervalt',
      actions: 'Acties',
    },
    previewTitle: 'Een maand bekijken of draaien',
    previewHint: 'Voorbeeld berekent de maand live en slaat niets op. Run bouwt de afrekening opnieuw op en factureert hem.',
    preview: 'Voorbeeld',
    run: 'Run',
    runTitle: 'Afrekening voor {period} draaien',
    runHint:
      'Bouwt de afrekening van deze maand opnieuw op en stuurt de Stripe-factuur naar de partner. Een afrekening die al is gefactureerd, betaald of vervallen kan niet opnieuw worden opgebouwd; laat hem eerst vervallen.',
    runSubmit: 'Draaien en factureren',
    ran: 'Afrekening gedraaid.',
    view: 'Bekijken',
    void: 'Laten vervallen',
    voidTitle: 'Afrekening voor {period} laten vervallen',
    voidHint: 'Markeert de afrekening als vervallen en annuleert de Stripe-factuur. De partner hoeft hem niet meer te betalen.',
    voidSubmit: 'Afrekening laten vervallen',
    voided: 'Afrekening vervallen.',
    invoice: 'Factuur',
    pdf: 'PDF',
    detailTitle: 'Afrekening {period}',
    totals: { resale: 'Klantprijzen', due: 'WeldSuite factureert', margin: 'Partner houdt' },
    lines: {
      workspace: 'Workspace',
      days: 'Dagen',
      seats: 'Gebruikers',
      resale: 'Verkoop',
      share: 'Aandeel',
      floor: 'Minimum',
      creditFloor: 'Credit-minimum',
      extraCredits: 'Extra credits',
      due: 'Verschuldigd',
      margin: 'Marge',
      empty: 'Geen regels.',
    },
    paidAt: 'Betaald {date}',
    dueAt: 'Vervalt {date}',
    close: 'Sluiten',
    loadFailed: 'De afrekening kon niet worden geladen.',
  },
  payment: {
    title: 'Betaalstatus',
    description:
      'Een onbetaalde factuur maakt de partner achterstallig en later alle workspaces alleen-lezen. Er wordt niets verwijderd. Betalen heft het op.',
    current: 'Huidige status',
    changedAt: 'Gewijzigd {date}',
    sweepStage: 'Aanmaningsfase',
    overdueInvoices: 'Achterstallige facturen',
    noneOverdue: 'Er is niets achterstallig.',
    daysOverdue: '{count} dagen te laat',
    due: 'vervallen op {date}',
    clock: 'Aanmaningsklok',
    clockRunning: 'Loopt',
    clockPaused: 'Gepauzeerd tot {date}',
    clockHint: 'Pauzeren houdt de partner op betaald, ook als een factuur achterstallig is, bijvoorbeeld bij een betalingsregeling.',
    thresholds: 'Achterstallig na {pastDue} dagen, workspaces alleen-lezen na {readOnly} dagen.',
    pause: 'Klok pauzeren',
    pauseTitle: 'De aanmaningsklok pauzeren',
    pauseHint: 'De klok loopt niet door tot het einde van de gekozen dag.',
    pauseFor: 'Pauzeren voor',
    pauseDays: '{count} dagen',
    pauseSubmit: 'Klok pauzeren',
    paused: 'Klok gepauzeerd.',
    resume: 'Klok hervatten',
    resumeTitle: 'De aanmaningsklok hervatten',
    resumeHint: 'Heft de pauze op. De volgende dagelijkse controle zet de partner in de fase die bij zijn achterstallige facturen hoort.',
    resumeSubmit: 'Klok hervatten',
    resumed: 'Klok hervat.',
    setStatus: 'Status instellen',
    setTitle: 'Betaalstatus instellen',
    setHint:
      'Een handmatige overschrijving. Opschorten zet alle workspaces van deze partner direct op alleen-lezen; terugzetten naar actief heft dat op. De volgende controle kan het opnieuw wijzigen als een factuur nog achterstallig is, pauzeer dus zo nodig ook de klok.',
    newStatus: 'Status',
    setSubmit: 'Status instellen',
    statusSet: 'Status bijgewerkt.',
  },
};

/**
 * Same locale source as the rest of the console (`getLocale()`, the i18n
 * cookie); anything but `nl` reads English.
 */
export function partnersCopy(): PartnersCopy {
  return getLocale() === 'nl' ? nl : en;
}

export const partnersCopyByLocale = { en, nl } as const;
