import { useParams, useNavigate } from '@tanstack/react-router';
import { PageLoader } from '@/components/page-loader';
import { Button } from '@weldsuite/ui/components/button';
import { Badge } from '@weldsuite/ui/components/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@weldsuite/ui/components/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@weldsuite/ui/components/table';
import { ArrowLeft } from 'lucide-react';
import {
  useAccountingJournalEntry,
  useDimensionValues,
  usePostJournalEntry,
} from '@/hooks/queries/use-accounting-queries';
import { useDocumentTexts } from '@/lib/weldbooks/use-document-texts';
import { useI18n } from '@/lib/i18n/provider';
import { useWeldbooksFormat } from '@/lib/weldbooks/use-weldbooks-format';

function journalStatusBadgeVariant(status: string): 'default' | 'destructive' | 'outline' {
  if (status === 'posted') return 'default';
  if (status === 'reversed') return 'destructive';
  return 'outline';
}

export default function JournalEntryDetailPage() {
  const { id } = useParams({ strict: false });
  const navigate = useNavigate();
  const { data, isLoading } = useAccountingJournalEntry(id!);
  const postEntry = usePostJournalEntry();
  const { t } = useI18n();
  const tj = t.accounting.journalEntry;
  const tsl = t.accounting.statusLabels.journalEntry;
  const td = useDocumentTexts().journal;
  const { formatMoney: fmt, formatDate } = useWeldbooksFormat();
  const { data: dimensionValues } = useDimensionValues();

  if (isLoading) return <PageLoader fullScreen={false} />;

  const entry = data?.data;
  if (!entry) {
    return (
      <div className="p-6 text-muted-foreground">{tj.notFound}</div>
    );
  }

  const lines = entry.lines ?? [];
  const dimensionName = (valueId: string | null | undefined) =>
    valueId ? (dimensionValues ?? []).find((value) => value.id === valueId)?.name : undefined;

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate({ to: '/weldbooks/journal' })}
          >
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-2xl font-semibold">
              {entry.entryNumber ?? tsl.fallback}
            </h1>
            <p className="text-sm text-muted-foreground">{formatDate(entry.date)}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Badge
            variant={journalStatusBadgeVariant(entry.status)}
          >
            {tsl[entry.status as keyof typeof tsl] ?? entry.status}
          </Badge>
          {entry.status === 'draft' && (
            <Button
              size="sm"
              onClick={() => postEntry.mutateAsync(entry.id)}
              disabled={postEntry.isPending}
            >
              {postEntry.isPending ? tj.posting : tj.postEntry}
            </Button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground">{tj.descriptionLabel}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm">{entry.description || '-'}</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground">{tj.sourceLabel}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm capitalize">{entry.sourceType?.replace('_', ' ') || tsl.sourceManual}</p>
            {entry.isAutomatic && (
              <Badge variant="outline" className="mt-1 text-xs">
                {tj.autoGenerated}
              </Badge>
            )}
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground">{tj.totalsLabel}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex justify-between text-sm">
              <span>{tj.debitLabel}</span>
              <span className="font-medium">{fmt(entry.totalDebit)}</span>
            </div>
            <div className="flex justify-between text-sm mt-1">
              <span>{tj.creditLabel}</span>
              <span className="font-medium">{fmt(entry.totalCredit)}</span>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">{tj.journalLines}</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{tj.account}</TableHead>
                <TableHead>{tj.description}</TableHead>
                <TableHead className="text-right">{tj.debit}</TableHead>
                <TableHead className="text-right">{tj.credit}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {lines.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={4} className="text-center text-muted-foreground">
                    {tj.noLines}
                  </TableCell>
                </TableRow>
              ) : (
                lines.map((line) => {
                  const dims = line as typeof line & { classId?: string | null; locationId?: string | null };
                  const className = dimensionName(dims.classId);
                  const locationName = dimensionName(dims.locationId);
                  return (
                  <TableRow key={line.id}>
                    <TableCell className="font-mono text-sm">{line.accountId}</TableCell>
                    <TableCell className="text-sm">
                      {line.description || '-'}
                      {(className || locationName) && (
                        <span className="block text-xs text-muted-foreground">
                          {[className && `${td.class}: ${className}`, locationName && `${td.location}: ${locationName}`]
                            .filter(Boolean)
                            .join(' · ')}
                        </span>
                      )}
                    </TableCell>
                    <TableCell className="text-right text-sm">
                      {Number(line.debit) > 0 ? fmt(line.debit, line.currency) : '-'}
                    </TableCell>
                    <TableCell className="text-right text-sm">
                      {Number(line.credit) > 0 ? fmt(line.credit, line.currency) : '-'}
                    </TableCell>
                  </TableRow>
                  );
                })
              )}
              <TableRow>
                <TableCell colSpan={2} className="text-right font-medium">
                  {tj.totals}
                </TableCell>
                <TableCell className="text-right font-semibold">{fmt(entry.totalDebit)}</TableCell>
                <TableCell className="text-right font-semibold">{fmt(entry.totalCredit)}</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
