/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/authorisation`; params?: Router.UnknownInputParams; } | { pathname: `/no-workspace`; params?: Router.UnknownInputParams; } | { pathname: `/sso-callback`; params?: Router.UnknownInputParams; } | { pathname: `/../../../platform/app/appstore/[code]/app-detail-client`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-tasks` | `/my-tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/project/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } } | { pathname: `/task/edit/[projectId]/[taskId]`, params: Router.UnknownInputParams & { projectId: string | number;taskId: string | number; } } | { pathname: `/task/new/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } } | { pathname: `/task/[projectId]/[taskId]`, params: Router.UnknownInputParams & { projectId: string | number;taskId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/authorisation`; params?: Router.UnknownOutputParams; } | { pathname: `/no-workspace`; params?: Router.UnknownOutputParams; } | { pathname: `/sso-callback`; params?: Router.UnknownOutputParams; } | { pathname: `/../../../platform/app/appstore/[code]/app-detail-client`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-tasks` | `/my-tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/project/[projectId]`, params: Router.UnknownOutputParams & { projectId: string; } } | { pathname: `/task/edit/[projectId]/[taskId]`, params: Router.UnknownOutputParams & { projectId: string;taskId: string; } } | { pathname: `/task/new/[projectId]`, params: Router.UnknownOutputParams & { projectId: string; } } | { pathname: `/task/[projectId]/[taskId]`, params: Router.UnknownOutputParams & { projectId: string;taskId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/authorisation${`?${string}` | `#${string}` | ''}` | `/no-workspace${`?${string}` | `#${string}` | ''}` | `/sso-callback${`?${string}` | `#${string}` | ''}` | `/../../../platform/app/appstore/[code]/app-detail-client${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-tasks${`?${string}` | `#${string}` | ''}` | `/my-tasks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/settings/privacy${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/authorisation`; params?: Router.UnknownInputParams; } | { pathname: `/no-workspace`; params?: Router.UnknownInputParams; } | { pathname: `/sso-callback`; params?: Router.UnknownInputParams; } | { pathname: `/../../../platform/app/appstore/[code]/app-detail-client`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-tasks` | `/my-tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownInputParams; } | `/project/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/task/edit/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/task/new/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/task/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/project/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } } | { pathname: `/task/edit/[projectId]/[taskId]`, params: Router.UnknownInputParams & { projectId: string | number;taskId: string | number; } } | { pathname: `/task/new/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } } | { pathname: `/task/[projectId]/[taskId]`, params: Router.UnknownInputParams & { projectId: string | number;taskId: string | number; } };
    }
  }
}
