export interface DrawerFieldDefinition {
  id: string;
  label: string;
  defaultVisible: boolean;
  required?: boolean;
}

export interface DrawerFieldConfig {
  panelName: string;
  label: string;
  fields: DrawerFieldDefinition[];
}

export const drawerFieldRegistry: Record<string, DrawerFieldConfig> = {
  'contact-detail': {
    panelName: 'panel:contact-detail',
    label: 'Contact Fields',
    fields: [
      { id: 'email', label: 'Email', defaultVisible: true },
      { id: 'phone', label: 'Phone', defaultVisible: true },
      { id: 'company', label: 'Company', defaultVisible: true },
      { id: 'status', label: 'Status', defaultVisible: true },
      { id: 'jobTitle', label: 'Job Title', defaultVisible: false },
      { id: 'department', label: 'Department', defaultVisible: false },
      { id: 'location', label: 'Location', defaultVisible: false },
      { id: 'lastContact', label: 'Last Contact', defaultVisible: false },
      { id: 'notes', label: 'Notes', defaultVisible: false },
    ],
  },
  'customer-detail': {
    panelName: 'panel:customer-detail',
    label: 'Customer Tabs',
    fields: [
      { id: 'overview', label: 'Details', defaultVisible: true, required: true },
      { id: 'activity', label: 'Activity', defaultVisible: true },
      { id: 'contacts', label: 'Contacts', defaultVisible: true },
      { id: 'emails', label: 'Emails', defaultVisible: true },
      { id: 'deals', label: 'Pipeline', defaultVisible: true },
      { id: 'calls', label: 'Calls', defaultVisible: false },
      { id: 'notes', label: 'Notes', defaultVisible: false },
      { id: 'meetings', label: 'Meetings', defaultVisible: false },
      { id: 'tasks', label: 'Tasks', defaultVisible: false },
      { id: 'files', label: 'Files', defaultVisible: false },
      { id: 'audit', label: 'Audit Log', defaultVisible: false },
    ],
  },
  'team-member-detail-panel': {
    panelName: 'panel:team-member-detail-panel:v2',
    label: 'Visible tabs',
    fields: [
      { id: 'profile', label: 'Details', defaultVisible: true, required: true },
      { id: 'messages', label: 'Messages', defaultVisible: true },
      { id: 'common', label: 'Common', defaultVisible: true },
      { id: 'activity', label: 'Activity', defaultVisible: false },
      { id: 'permissions', label: 'Permissions', defaultVisible: false },
    ],
  },
  'domain-detail-panel': {
    panelName: 'panel:domain-detail-panel',
    label: 'Visible tabs',
    fields: [
      { id: 'details', label: 'Details', defaultVisible: true, required: true },
      { id: 'nameservers', label: 'Nameservers', defaultVisible: true },
      { id: 'settings', label: 'Settings', defaultVisible: true },
      { id: 'history', label: 'History', defaultVisible: true },
    ],
  },
  'task-detail': {
    panelName: 'panel:task-detail',
    label: 'Task Fields',
    fields: [
      { id: 'status', label: 'Status', defaultVisible: true, required: true },
      { id: 'priority', label: 'Priority', defaultVisible: true },
      { id: 'assignee', label: 'Assignee', defaultVisible: true },
      { id: 'dueDate', label: 'Due Date', defaultVisible: true },
      { id: 'subtasks', label: 'Subtasks', defaultVisible: true },
      { id: 'labels', label: 'Labels', defaultVisible: true },
      { id: 'company', label: 'Company', defaultVisible: false },
      { id: 'repeat', label: 'Repeat', defaultVisible: true },
      { id: 'dependencies', label: 'Dependencies', defaultVisible: false },
      { id: 'attachments', label: 'Attachments', defaultVisible: false },
      { id: 'created', label: 'Created', defaultVisible: false },
    ],
  },
  'project-detail': {
    panelName: 'panel:project-detail',
    label: 'Project Fields',
    fields: [
      { id: 'status', label: 'Status', defaultVisible: true, required: true },
      { id: 'priority', label: 'Priority', defaultVisible: true },
      { id: 'health', label: 'Health', defaultVisible: true },
      { id: 'progress', label: 'Progress', defaultVisible: true },
      { id: 'manager', label: 'Manager', defaultVisible: true },
      { id: 'customer', label: 'Customer', defaultVisible: true },
      { id: 'startDate', label: 'Start Date', defaultVisible: true },
      { id: 'endDate', label: 'End Date', defaultVisible: true },
      { id: 'tasksSummary', label: 'Tasks Summary', defaultVisible: true },
      { id: 'milestonesSummary', label: 'Milestones Summary', defaultVisible: false },
      { id: 'budgetHours', label: 'Budget Hours', defaultVisible: true },
      { id: 'budgetAmount', label: 'Budget Amount', defaultVisible: false },
      { id: 'hourlyRate', label: 'Hourly Rate', defaultVisible: false },
      { id: 'type', label: 'Type', defaultVisible: false },
      { id: 'methodology', label: 'Methodology', defaultVisible: false },
      { id: 'visibility', label: 'Visibility', defaultVisible: false },
      { id: 'members', label: 'Members', defaultVisible: true },
      { id: 'tasksList', label: 'Tasks List', defaultVisible: false },
    ],
  },
  'helpdesk-contact-detail': {
    panelName: 'panel:helpdesk-contact-detail',
    label: 'Contact Fields',
    fields: [
      { id: 'firstName', label: 'First Name', defaultVisible: true, required: true },
      { id: 'lastName', label: 'Last Name', defaultVisible: true, required: true },
      { id: 'email', label: 'Email', defaultVisible: true },
      { id: 'phone', label: 'Phone', defaultVisible: true },
      { id: 'mobile', label: 'Mobile', defaultVisible: true },
      { id: 'notes', label: 'Notes', defaultVisible: false },
      { id: 'location', label: 'Visitor Location', defaultVisible: true },
      { id: 'timezone', label: 'Timezone', defaultVisible: false },
      { id: 'tags', label: 'Tags', defaultVisible: true },
    ],
  },
  'customer-sidebar-fields': {
    panelName: 'panel:customer-sidebar-fields',
    label: 'Customer Fields',
    fields: [
      { id: 'name', label: 'Name', defaultVisible: true, required: true },
      { id: 'description', label: 'Notes', defaultVisible: true },
      { id: 'domains', label: 'Domains', defaultVisible: true },
      { id: 'owner', label: 'Owner', defaultVisible: true },
      { id: 'accountManager', label: 'Account Manager', defaultVisible: true },
      { id: 'email', label: 'Email', defaultVisible: true },
      { id: 'phone', label: 'Phone', defaultVisible: true },
      { id: 'mobile', label: 'Mobile', defaultVisible: true },
      { id: 'team', label: 'Team', defaultVisible: false },
      { id: 'linkedinUrl', label: 'LinkedIn', defaultVisible: false },
      { id: 'twitterHandle', label: 'Twitter', defaultVisible: false },
      { id: 'employeeCount', label: 'Employees', defaultVisible: false },
      { id: 'preferredLanguage', label: 'Language', defaultVisible: false },
      { id: 'vatNumber', label: 'VAT Number', defaultVisible: false },
      { id: 'registrationNumber', label: 'Reg. Number', defaultVisible: false },
      { id: 'paymentTerms', label: 'Payment Terms', defaultVisible: false },
      { id: 'currency', label: 'Currency', defaultVisible: false },
      { id: 'source', label: 'Source', defaultVisible: false },
      { id: 'categories', label: 'Categories', defaultVisible: true },
      { id: 'industry', label: 'Industry', defaultVisible: true },
      { id: 'type', label: 'Type', defaultVisible: false },
      { id: 'status', label: 'Status', defaultVisible: false },
      { id: 'lifecycleStage', label: 'Lifecycle Stage', defaultVisible: false },
      { id: 'segment', label: 'Segment', defaultVisible: false },
      { id: 'rating', label: 'Rating', defaultVisible: false },
      { id: 'lastContactDate', label: 'Last Contact', defaultVisible: false },
      { id: 'relationshipSince', label: 'Customer Since', defaultVisible: false },
      { id: 'nextFollowUpDate', label: 'Next Follow-up', defaultVisible: false },
      { id: 'lifetimeValue', label: 'LTV', defaultVisible: false },
      { id: 'leadScore', label: 'Lead Score', defaultVisible: false },
      { id: 'npsScore', label: 'NPS Score', defaultVisible: false },
      { id: 'address', label: 'Billing Address', defaultVisible: true },
      { id: 'contacts', label: 'Linked Contacts', defaultVisible: true },
      { id: 'lists', label: 'Lists', defaultVisible: false },
    ],
  },
  'ticket-sidebar': {
    panelName: 'panel:ticket-sidebar',
    label: 'Ticket Fields',
    fields: [
      { id: 'status', label: 'Status', defaultVisible: true, required: true },
      { id: 'priority', label: 'Priority', defaultVisible: true },
      { id: 'assignee', label: 'Assignee', defaultVisible: true },
      { id: 'type', label: 'Type', defaultVisible: true },
      { id: 'channel', label: 'Channel', defaultVisible: true },
      { id: 'created', label: 'Created', defaultVisible: true },
      { id: 'customer', label: 'Customer', defaultVisible: true },
      { id: 'tags', label: 'Tags', defaultVisible: true },
      { id: 'linkedReports', label: 'Linked Reports', defaultVisible: false },
      { id: 'linkedConversations', label: 'Linked Conversations', defaultVisible: false },
    ],
  },
};
