-- WeldPass — encrypted secret vaults with sync to Cloudflare and Vercel.
--
-- Generated by drizzle-kit from packages/core/db/src/schema/weldpass.ts, with
-- IF NOT EXISTS added: the tenant sweep runs across every workspace database
-- and has to survive being re-run after a partial failure.
--
-- Values are never stored in the clear. Each secret carries its own wrapped
-- data key (dek_wrapped); the project KEK (weldpass_projects.kek_wrapped) wraps
-- those, and the worker's WELDPASS_ROOT_KEY wraps the KEK — so none of this is
-- readable from a database dump alone.

CREATE TABLE IF NOT EXISTS "weldpass_projects" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"workspace_id" varchar(255) NOT NULL,
	"name" varchar(100) NOT NULL,
	"slug" varchar(60) NOT NULL,
	"description" text,
	"kek_wrapped" text NOT NULL,
	"root_key_version" varchar(10) DEFAULT 'v1' NOT NULL,
	"created_by" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_projects_workspace_idx" ON "weldpass_projects" USING btree ("workspace_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "weldpass_projects_workspace_slug_idx" ON "weldpass_projects" USING btree ("workspace_id","slug");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "weldpass_environments" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"project_id" varchar(30) NOT NULL,
	"name" varchar(60) NOT NULL,
	"slug" varchar(40) NOT NULL,
	"is_production" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_environments_project_idx" ON "weldpass_environments" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "weldpass_environments_project_slug_idx" ON "weldpass_environments" USING btree ("project_id","slug");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "weldpass_secrets" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"project_id" varchar(30) NOT NULL,
	"environment_id" varchar(30) NOT NULL,
	"key" varchar(255) NOT NULL,
	"ciphertext" text NOT NULL,
	"dek_wrapped" text NOT NULL,
	"checksum" varchar(64) NOT NULL,
	"value_length" integer DEFAULT 0 NOT NULL,
	"value_hint" varchar(8),
	"note" text,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_secrets_project_idx" ON "weldpass_secrets" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_secrets_environment_idx" ON "weldpass_secrets" USING btree ("environment_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "weldpass_secrets_environment_key_idx" ON "weldpass_secrets" USING btree ("environment_id","key");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "weldpass_secret_versions" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"secret_id" varchar(30) NOT NULL,
	"project_id" varchar(30) NOT NULL,
	"version" integer NOT NULL,
	"action" varchar(20) NOT NULL,
	"ciphertext" text NOT NULL,
	"dek_wrapped" text NOT NULL,
	"checksum" varchar(64) NOT NULL,
	"created_by" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_secret_versions_secret_idx" ON "weldpass_secret_versions" USING btree ("secret_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "weldpass_secret_versions_secret_version_idx" ON "weldpass_secret_versions" USING btree ("secret_id","version");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "weldpass_provider_credentials" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"project_id" varchar(30) NOT NULL,
	"provider" varchar(30) NOT NULL,
	"name" varchar(100) NOT NULL,
	"ciphertext" text NOT NULL,
	"dek_wrapped" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"last_verified_at" timestamp with time zone,
	"last_verify_error" text,
	"created_by" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_provider_credentials_project_idx" ON "weldpass_provider_credentials" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_provider_credentials_provider_idx" ON "weldpass_provider_credentials" USING btree ("provider");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "weldpass_sync_targets" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"project_id" varchar(30) NOT NULL,
	"environment_id" varchar(30) NOT NULL,
	"credential_id" varchar(30) NOT NULL,
	"provider" varchar(30) NOT NULL,
	"name" varchar(100) NOT NULL,
	"config" jsonb NOT NULL,
	"auto_sync" boolean DEFAULT false NOT NULL,
	"prune" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'idle' NOT NULL,
	"last_synced_at" timestamp with time zone,
	"last_synced_count" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"created_by" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_sync_targets_project_idx" ON "weldpass_sync_targets" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_sync_targets_environment_idx" ON "weldpass_sync_targets" USING btree ("environment_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_sync_targets_credential_idx" ON "weldpass_sync_targets" USING btree ("credential_id");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "weldpass_sync_runs" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"target_id" varchar(30) NOT NULL,
	"project_id" varchar(30) NOT NULL,
	"environment_id" varchar(30) NOT NULL,
	"status" varchar(20) NOT NULL,
	"trigger" varchar(20) NOT NULL,
	"pushed" integer DEFAULT 0 NOT NULL,
	"removed" integer DEFAULT 0 NOT NULL,
	"failed" integer DEFAULT 0 NOT NULL,
	"error" text,
	"details" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"triggered_by" varchar(255),
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_sync_runs_target_idx" ON "weldpass_sync_runs" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_sync_runs_project_idx" ON "weldpass_sync_runs" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_sync_runs_started_at_idx" ON "weldpass_sync_runs" USING btree ("started_at");--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "weldpass_audit_events" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"project_id" varchar(30) NOT NULL,
	"environment_id" varchar(30),
	"secret_id" varchar(30),
	"actor_id" varchar(255) NOT NULL,
	"action" varchar(40) NOT NULL,
	"target_key" varchar(255),
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ip" varchar(45),
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_audit_events_project_idx" ON "weldpass_audit_events" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_audit_events_secret_idx" ON "weldpass_audit_events" USING btree ("secret_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weldpass_audit_events_created_at_idx" ON "weldpass_audit_events" USING btree ("created_at");
