-- WeldHR — employee operations and the workforce portal.
--
-- Generated by drizzle-kit from packages/core/db/src/schema/weldhr.ts, with
-- IF NOT EXISTS added: the tenant sweep runs across every workspace database
-- and has to survive being re-run after a partial failure. New tables only;
-- nothing existing is altered.
--
-- hr_employees.sensitive_encrypted holds the AES-GCM blob of an employee's
-- personal data (DATABASE_ENCRYPTION_KEY), so it is not readable from a dump.
-- Employee ↔ client account is hr_client_assignments.company_id → companies.id
-- (no FK, matching the rest of the tenant schema).

CREATE TABLE IF NOT EXISTS "hr_attendance_records" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"company_id" varchar(30),
	"shift_id" varchar(30),
	"date" date NOT NULL,
	"clock_in" timestamp with time zone,
	"clock_out" timestamp with time zone,
	"break_minutes" integer DEFAULT 0 NOT NULL,
	"worked_minutes" integer,
	"late_minutes" integer DEFAULT 0 NOT NULL,
	"status" varchar(20) DEFAULT 'present' NOT NULL,
	"source" varchar(20) DEFAULT 'manual' NOT NULL,
	"notes" text,
	"approved_by" varchar(255),
	"approved_at" timestamp,
	"created_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_audit_events" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"actor_id" varchar(255) NOT NULL,
	"action" varchar(60) NOT NULL,
	"employee_id" varchar(30),
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ip" varchar(64),
	"created_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_checklist_tasks" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"checklist_id" varchar(30) NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"assignee_role" varchar(20) DEFAULT 'hr' NOT NULL,
	"assignee_user_id" varchar(255),
	"due_date" date,
	"visible_to_employee" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"completed_at" timestamp,
	"completed_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_checklist_templates" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"name" varchar(160) NOT NULL,
	"description" text,
	"kind" varchar(20) DEFAULT 'onboarding' NOT NULL,
	"department_id" varchar(30),
	"items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_checklists" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"template_id" varchar(30),
	"kind" varchar(20) NOT NULL,
	"name" varchar(160) NOT NULL,
	"status" varchar(20) DEFAULT 'in_progress' NOT NULL,
	"started_by" varchar(255),
	"started_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_client_assignments" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"company_id" varchar(30) NOT NULL,
	"role" varchar(120),
	"allocation_percent" double precision DEFAULT 100 NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date,
	"notes" text,
	"created_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_coaching_logs" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"company_id" varchar(30),
	"coach_user_id" varchar(255),
	"coach_name" varchar(255),
	"session_date" date NOT NULL,
	"category" varchar(20) DEFAULT 'performance' NOT NULL,
	"topic" varchar(255) NOT NULL,
	"notes" text,
	"action_items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"follow_up_date" date,
	"status" varchar(20) DEFAULT 'open' NOT NULL,
	"visibility" varchar(20) DEFAULT 'employee' NOT NULL,
	"acknowledged_at" timestamp,
	"employee_comment" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_departments" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text,
	"parent_id" varchar(30),
	"head_employee_id" varchar(30),
	"color" varchar(20),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_employees" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_number" varchar(50),
	"first_name" varchar(120) NOT NULL,
	"last_name" varchar(120) NOT NULL,
	"preferred_name" varchar(120),
	"email" varchar(255) NOT NULL,
	"phone" varchar(50),
	"avatar_url" varchar(500),
	"pronouns" varchar(40),
	"job_title" varchar(160),
	"department_id" varchar(30),
	"manager_id" varchar(30),
	"user_id" varchar(255),
	"employment_type" varchar(20) DEFAULT 'full_time' NOT NULL,
	"status" varchar(20) DEFAULT 'onboarding' NOT NULL,
	"start_date" date,
	"end_date" date,
	"probation_end_date" date,
	"location" varchar(160),
	"timezone" varchar(60),
	"weekly_hours" double precision,
	"sensitive_encrypted" text,
	"custom_fields" jsonb,
	"created_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_evaluation_forms" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"name" varchar(160) NOT NULL,
	"description" text,
	"criteria" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_evaluations" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"form_id" varchar(30) NOT NULL,
	"company_id" varchar(30),
	"evaluator_user_id" varchar(255),
	"evaluator_name" varchar(255),
	"period_start" date,
	"period_end" date,
	"criteria" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"scores" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"overall_score" double precision,
	"summary" text,
	"status" varchar(20) DEFAULT 'draft' NOT NULL,
	"shared_with_client" boolean DEFAULT false NOT NULL,
	"submitted_at" timestamp,
	"acknowledged_at" timestamp,
	"employee_comment" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_kpi_definitions" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text,
	"unit" varchar(20) DEFAULT 'number' NOT NULL,
	"direction" varchar(20) DEFAULT 'higher_better' NOT NULL,
	"target" double precision,
	"company_id" varchar(30),
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_kpi_values" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"kpi_id" varchar(30) NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"company_id" varchar(30),
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"value" double precision NOT NULL,
	"source" varchar(20) DEFAULT 'manual' NOT NULL,
	"shared_with_client" boolean DEFAULT false NOT NULL,
	"created_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_leave_allowances" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"leave_type_id" varchar(30) NOT NULL,
	"year" integer NOT NULL,
	"days" double precision NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_leave_requests" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"leave_type_id" varchar(30) NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"days" double precision NOT NULL,
	"reason" text,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"requested_by" varchar(255),
	"reviewed_by" varchar(255),
	"reviewed_at" timestamp,
	"review_note" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_leave_types" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"name" varchar(120) NOT NULL,
	"color" varchar(20),
	"is_paid" boolean DEFAULT true NOT NULL,
	"requires_approval" boolean DEFAULT true NOT NULL,
	"default_allowance_days" double precision,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_milestones" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"company_id" varchar(30),
	"title" varchar(255) NOT NULL,
	"description" text,
	"type" varchar(20) DEFAULT 'milestone' NOT NULL,
	"status" varchar(20) DEFAULT 'planned' NOT NULL,
	"due_date" date,
	"achieved_at" date,
	"shared_with_client" boolean DEFAULT false NOT NULL,
	"created_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_portal_access" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"kind" varchar(20) NOT NULL,
	"employee_id" varchar(30),
	"person_id" varchar(30),
	"company_id" varchar(30),
	"email" varchar(255) NOT NULL,
	"display_name" varchar(255),
	"status" varchar(20) DEFAULT 'invited' NOT NULL,
	"invited_by" varchar(255),
	"invited_at" timestamp,
	"last_login_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_portal_settings" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"employee_portal_enabled" boolean DEFAULT true NOT NULL,
	"client_portal_enabled" boolean DEFAULT true NOT NULL,
	"display_name" varchar(255),
	"logo_url" varchar(500),
	"favicon_url" varchar(500),
	"primary_color" varchar(20),
	"accent_color" varchar(20),
	"welcome_message" text,
	"support_email" varchar(255),
	"hide_weldsuite_branding" boolean DEFAULT true NOT NULL,
	"custom_domain" varchar(255),
	"client_can_see_individual_scores" boolean DEFAULT true NOT NULL,
	"employee_self_clock_in" boolean DEFAULT true NOT NULL,
	"employee_leave_requests" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hr_shifts" (
	"id" varchar(30) PRIMARY KEY NOT NULL,
	"employee_id" varchar(30) NOT NULL,
	"company_id" varchar(30),
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"notes" text,
	"created_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_attendance_employee_date_idx" ON "hr_attendance_records" USING btree ("employee_id","date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_attendance_date_idx" ON "hr_attendance_records" USING btree ("date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_attendance_company_idx" ON "hr_attendance_records" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_audit_events_employee_idx" ON "hr_audit_events" USING btree ("employee_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_audit_events_created_idx" ON "hr_audit_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_tasks_checklist_idx" ON "hr_checklist_tasks" USING btree ("checklist_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_tasks_employee_idx" ON "hr_checklist_tasks" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_tasks_due_idx" ON "hr_checklist_tasks" USING btree ("due_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklist_templates_kind_idx" ON "hr_checklist_templates" USING btree ("kind");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklists_employee_idx" ON "hr_checklists" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_checklists_status_idx" ON "hr_checklists" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_client_assignments_employee_idx" ON "hr_client_assignments" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_client_assignments_company_idx" ON "hr_client_assignments" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_coaching_logs_employee_idx" ON "hr_coaching_logs" USING btree ("employee_id","session_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_coaching_logs_follow_up_idx" ON "hr_coaching_logs" USING btree ("follow_up_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_coaching_logs_status_idx" ON "hr_coaching_logs" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_departments_parent_idx" ON "hr_departments" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_employees_status_idx" ON "hr_employees" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_employees_department_idx" ON "hr_employees" USING btree ("department_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_employees_manager_idx" ON "hr_employees" USING btree ("manager_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_employees_email_idx" ON "hr_employees" USING btree ("email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_employees_user_idx" ON "hr_employees" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_employees_created_idx" ON "hr_employees" USING btree ("created_at","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_evaluations_employee_idx" ON "hr_evaluations" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_evaluations_status_idx" ON "hr_evaluations" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_evaluations_company_idx" ON "hr_evaluations" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_kpi_values_employee_idx" ON "hr_kpi_values" USING btree ("employee_id","period_start");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_kpi_values_kpi_idx" ON "hr_kpi_values" USING btree ("kpi_id","period_start");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_kpi_values_company_idx" ON "hr_kpi_values" USING btree ("company_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "hr_leave_allowances_uidx" ON "hr_leave_allowances" USING btree ("employee_id","leave_type_id","year");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_leave_requests_employee_idx" ON "hr_leave_requests" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_leave_requests_status_idx" ON "hr_leave_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_leave_requests_start_idx" ON "hr_leave_requests" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_milestones_employee_idx" ON "hr_milestones" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_milestones_company_idx" ON "hr_milestones" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_portal_access_email_idx" ON "hr_portal_access" USING btree ("email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_portal_access_employee_idx" ON "hr_portal_access" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_portal_access_company_idx" ON "hr_portal_access" USING btree ("company_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "hr_portal_access_kind_email_company_uidx" ON "hr_portal_access" USING btree ("kind","email","company_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_shifts_employee_start_idx" ON "hr_shifts" USING btree ("employee_id","starts_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hr_shifts_start_idx" ON "hr_shifts" USING btree ("starts_at");
