import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  errorText: { fontSize: 16 },

  // Top header bar — h-[53px] equivalent, border-b border-gray-200, px-3
  topHeader: {
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  topHeaderRow: {
    height: 53,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  topHeaderBack: {
    width: 34,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: -4,
    borderRadius: 7,
  },
  topHeaderSubject: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: -0.2,
    marginLeft: 4,
  },
  topHeaderThreadBadge: {
    height: 20,
    minWidth: 20,
    paddingHorizontal: 4,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topHeaderThreadBadgeText: {
    color: '#6B7280',
    fontSize: 10,
    fontWeight: '500',
    fontFamily: 'Menlo',
  },
  topHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  topHeaderIconBtn: {
    width: 31,
    height: 31,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 7,
  },

  scrollView: { flex: 1 },

  // Subject block — large heading just below the top bar, above the sender
  subjectBlock: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 12,
    paddingTop: 16,
    paddingBottom: 10,
    gap: 10,
  },
  subjectText: {
    flex: 1,
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 30,
    letterSpacing: -0.4,
  },
  subjectThreadBadge: {
    height: 22,
    minWidth: 22,
    paddingHorizontal: 6,
    borderRadius: 7,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
  },
  subjectThreadBadgeText: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '600',
    fontFamily: 'Menlo',
  },

  // Sender header — px-3 py-3 md:py-4
  senderHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 14,
    gap: 8,
  },
  senderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1, minWidth: 0 },
  senderAvatar: {
    width: 32,
    height: 32,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  senderAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  senderInfo: { flex: 1, minWidth: 0 },
  senderLineWrap: { flexDirection: 'row', alignItems: 'center', gap: 1, flexWrap: 'wrap' },
  senderName: {
    fontSize: 14.5,
    fontWeight: '600',
    flexShrink: 1,
  },
  senderToWord: {
    fontSize: 14.5,
    color: '#6B7280',
    marginLeft: 5,
  },
  senderRecipientWrap: { flexDirection: 'row', alignItems: 'center', gap: 4, flexShrink: 1, minWidth: 0 },
  senderRecipientEmail: {
    fontSize: 14.5,
    color: '#2563EB',
    flexShrink: 1,
  },
  senderDate: {
    fontSize: 13,
    color: '#374151',
    paddingTop: 4,
    flexShrink: 0,
  },

  // Details panel — collapsible "from/to/date" block
  detailsPanel: {
    marginHorizontal: 12,
    marginBottom: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 12,
    paddingHorizontal: 14,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F3F4F6',
    gap: 10,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6B7280',
    width: 36,
    paddingTop: 1,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  detailValue: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  detailName: { fontSize: 13, fontWeight: '600' },
  detailEmail: { fontSize: 13, color: '#6B7280' },
  detailEmailLine: { fontSize: 13, flex: 1 },

  // Body — px-3, text-sm, leading-relaxed (line-height: 1.625)
  bodySection: { paddingHorizontal: 12, paddingBottom: 16 },
  body: { fontSize: 14, lineHeight: 23, color: '#374151' },
  webViewBody: { backgroundColor: 'transparent', opacity: 0.99 },

  // Attachments — mt-6 uppercase tracking-wide header + chips
  attachmentsBlock: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
  },
  attachmentsHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  attachmentsHeaderText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#6B7280',
    letterSpacing: 0.8,
  },
  // Horizontal rail of Gmail-style attachment cards
  attachmentRail: { gap: 8, paddingRight: 12 },
  attachmentCard: {
    width: 210,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
  },
  attachmentCardIcon: {
    width: 36,
    height: 36,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  attachmentCardMeta: { flex: 1, minWidth: 0 },
  attachmentCardName: { fontSize: 13, fontWeight: '500' },
  attachmentCardSub: { fontSize: 11, color: '#9CA3AF', marginTop: 2 },

  // Floating Reply/Forward toolbar — pinned to the bottom, elevated above the
  // full-screen email content (Outlook style).
  actionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
    // Shadow lifts the bar off the scrolling email so it reads as floating.
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 12,
  },
  actionBarBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
  },
  actionBarText: { fontSize: 13, fontWeight: '600' },

  // Thread section
  threadSection: { paddingHorizontal: 12, paddingTop: 12, gap: 12 },

  // ThreadMessage component — collapsed/expanded card matches platform `border border-border/50 rounded-lg bg-muted/50`
  threadCollapsed: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(229,231,235,0.6)',
    borderRadius: 10,
    backgroundColor: '#F9FAFB',
    gap: 10,
  },
  threadAvatar: { width: 24, height: 24, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  threadAvatarText: { fontSize: 11, fontWeight: '600', color: '#FFFFFF' },
  threadCollapsedContent: { flex: 1, minWidth: 0 },
  threadDateGroup: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  threadSenderName: { fontSize: 14, fontWeight: '600' },
  threadPreview: { fontSize: 12.5, marginTop: 2 },
  threadDate: { fontSize: 12 },
  threadExpanded: {
    paddingHorizontal: 12,
    paddingBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(229,231,235,0.6)',
    borderRadius: 10,
    backgroundColor: '#F9FAFB',
  },
  threadExpandedHeader: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, gap: 10 },
  threadExpandedSender: { flex: 1, minWidth: 0 },
  threadRecipientText: { fontSize: 12.5, marginTop: 2 },
  threadBody: { paddingLeft: 0, paddingRight: 4, paddingBottom: 8 },
  threadBodyText: { fontSize: 14, lineHeight: 22 },
  threadActions: { flexDirection: 'row', gap: 8, paddingLeft: 0, paddingTop: 4 },
  threadActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  threadActionText: { fontSize: 13, fontWeight: '500' },
});
