import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  splitContainer: {
    flex: 1,
    flexDirection: 'row',
  },
  container: {
    flex: 1,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listRegion: {
    flex: 1,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 14,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  loadingTextInline: {
    fontSize: 14,
  },
  outlookHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingBottom: 8,
    gap: 6,
  },
  outlookHeaderIcon: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: -8,
  },
  outlookHeaderTitle: {
    flex: 1,
    fontSize: 26,
    fontWeight: '600',
    lineHeight: 32,
    letterSpacing: -0.4,
    marginLeft: -2,
  },
  outlookHeaderAvatar: {
    width: 32,
    height: 32,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  outlookHeaderAvatarText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  waSearchContainer: {
    paddingHorizontal: 12,
    paddingTop: 2,
    paddingBottom: 6,
  },
  waSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    height: 40,
    borderRadius: 12,
    gap: 12,
  },
  waSearchPlaceholder: {
    flex: 1,
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: -0.1,
  },
  waChipsRow: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 10,
    gap: 6,
  },
  waChip: {
    paddingHorizontal: 15,
    height: 33,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  waChipText: {
    fontSize: 14,
    letterSpacing: -0.1,
  },
  listContainer: {
    paddingBottom: 96,
  },
  sectionHeader: {
    paddingHorizontal: 12,
    paddingTop: 16,
    paddingBottom: 6,
  },
  sectionHeaderText: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: -0.1,
    color: '#374151',
  },
  emailItem: {
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 11,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  avatarWrap: {
    position: 'relative',
    marginTop: 3,
    flexShrink: 0,
  },
  avatar: {
    width: 33,
    height: 33,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  unreadDot: {
    position: 'absolute',
    top: '50%',
    marginTop: -3,
    left: -10,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#2563EB',
  },
  emailContent: {
    flex: 1,
    minWidth: 0,
  },
  emailTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  senderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  senderName: {
    fontSize: 15,
    lineHeight: 20,
    flexShrink: 1,
  },
  threadCountBadge: {
    height: 18,
    minWidth: 18,
    paddingHorizontal: 2,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  threadCountText: {
    color: '#6B7280',
    fontSize: 10,
    fontWeight: '500',
    fontFamily: 'Menlo',
  },
  emailMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  emailTime: {
    fontSize: 11.5,
    lineHeight: 14,
    fontWeight: '400',
  },
  subject: {
    fontSize: 14,
    lineHeight: 20,
    marginTop: 1,
  },
  preview: {
    fontSize: 14,
    lineHeight: 18,
    marginTop: 2,
    fontWeight: '400',
  },
  unreadCountPill: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 999,
    backgroundColor: '#EFF6FF',
  },
  unreadCountPillText: {
    fontSize: 10,
    fontWeight: '500',
    color: '#2563EB',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 160,
    paddingHorizontal: 32,
  },
  emptyIllustrationWrapper: {
    width: 220,
    height: 155,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyText: {
    fontSize: 17,
    fontWeight: '600',
    marginTop: 0,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 15,
    marginTop: 7,
    textAlign: 'center',
  },
  snackbar: {
    position: 'absolute',
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 20,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
    zIndex: 10,
  },
  snackbarText: {
    flex: 1,
    color: '#F3F4F6',
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: -0.1,
  },
  snackbarAction: {
    color: '#93C5FD',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.1,
  },
  fab: {
    position: 'absolute',
    right: 16,
    height: 56,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 6,
  },
  fabInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 20,
    height: 56,
  },
  fabLabel: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.1,
  },
  swipeActionsContainer: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  swipeAction: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 76,
    paddingHorizontal: 8,
  },
  swipeActionText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 4,
  },
  labelBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 8,
  },
  labelBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  labelBadgeText: {
    fontSize: 12,
    fontWeight: '500',
  },
  labelOverflow: {
    fontSize: 10,
    alignSelf: 'center',
  },
});
