// Mock data for testing without backend
export const mockProducts = [
  {
    id: '1',
    title: 'Premium Wireless Headphones',
    description: 'High-quality wireless headphones with active noise cancellation and 30-hour battery life.',
    price: 199.99,
    compareAtPrice: 299.99,
    featuredImageUrl: 'https://via.placeholder.com/300x300/4A90E2/FFFFFF?text=Headphones',
    quantityAvailable: 50,
    categoryName: 'Electronics',
    sku: 'WH-001',
  },
  {
    id: '2',
    title: 'Smart Watch Pro',
    description: 'Advanced fitness tracking, heart rate monitoring, and smartphone connectivity.',
    price: 349.99,
    compareAtPrice: 449.99,
    featuredImageUrl: 'https://via.placeholder.com/300x300/E24A4A/FFFFFF?text=Smart+Watch',
    quantityAvailable: 30,
    categoryName: 'Electronics',
    sku: 'SW-002',
  },
  {
    id: '3',
    title: 'Organic Cotton T-Shirt',
    description: 'Comfortable and sustainable organic cotton t-shirt in various colors.',
    price: 29.99,
    featuredImageUrl: 'https://via.placeholder.com/300x300/4AE290/FFFFFF?text=T-Shirt',
    quantityAvailable: 100,
    categoryName: 'Clothing',
    sku: 'TS-003',
  },
  {
    id: '4',
    title: 'Professional Camera Lens',
    description: '50mm f/1.8 prime lens for professional photography.',
    price: 599.99,
    compareAtPrice: 799.99,
    featuredImageUrl: 'https://via.placeholder.com/300x300/E2904A/FFFFFF?text=Camera+Lens',
    quantityAvailable: 15,
    categoryName: 'Photography',
    sku: 'CL-004',
  },
  {
    id: '5',
    title: 'Yoga Mat Premium',
    description: 'Non-slip, eco-friendly yoga mat with alignment markers.',
    price: 49.99,
    featuredImageUrl: 'https://via.placeholder.com/300x300/9C4AE2/FFFFFF?text=Yoga+Mat',
    quantityAvailable: 75,
    categoryName: 'Sports',
    sku: 'YM-005',
  },
  {
    id: '6',
    title: 'Coffee Maker Deluxe',
    description: 'Programmable coffee maker with thermal carafe and auto-shutoff.',
    price: 89.99,
    compareAtPrice: 129.99,
    featuredImageUrl: 'https://via.placeholder.com/300x300/8B4513/FFFFFF?text=Coffee+Maker',
    quantityAvailable: 40,
    categoryName: 'Home & Kitchen',
    sku: 'CM-006',
  },
];

export const mockCategories = [
  {
    id: '1',
    name: 'Electronics',
    description: 'Latest gadgets and electronic devices',
    imageUrl: 'https://via.placeholder.com/300x300/4A90E2/FFFFFF?text=Electronics',
    productCount: 25,
  },
  {
    id: '2',
    name: 'Clothing',
    description: 'Fashion and apparel for all seasons',
    imageUrl: 'https://via.placeholder.com/300x300/4AE290/FFFFFF?text=Clothing',
    productCount: 50,
  },
  {
    id: '3',
    name: 'Photography',
    description: 'Cameras, lenses, and accessories',
    imageUrl: 'https://via.placeholder.com/300x300/E2904A/FFFFFF?text=Photography',
    productCount: 15,
  },
  {
    id: '4',
    name: 'Sports',
    description: 'Sports equipment and fitness gear',
    imageUrl: 'https://via.placeholder.com/300x300/9C4AE2/FFFFFF?text=Sports',
    productCount: 30,
  },
  {
    id: '5',
    name: 'Home & Kitchen',
    description: 'Everything for your home',
    imageUrl: 'https://via.placeholder.com/300x300/8B4513/FFFFFF?text=Home',
    productCount: 45,
  },
  {
    id: '6',
    name: 'Books',
    description: 'Literature, education, and entertainment',
    imageUrl: 'https://via.placeholder.com/300x300/FF6347/FFFFFF?text=Books',
    productCount: 100,
  },
];

export const mockOrders = [
  {
    id: '1',
    orderNumber: 'ORD-2024-001',
    status: 'delivered',
    totalAmount: 549.98,
    itemCount: 2,
    createdAt: new Date('2024-01-15').toISOString(),
    shippingAddress: '123 Main St, New York, NY 10001',
  },
  {
    id: '2',
    orderNumber: 'ORD-2024-002',
    status: 'shipped',
    totalAmount: 89.99,
    itemCount: 1,
    createdAt: new Date('2024-01-20').toISOString(),
    shippingAddress: '456 Oak Ave, Los Angeles, CA 90001',
  },
  {
    id: '3',
    orderNumber: 'ORD-2024-003',
    status: 'pending',
    totalAmount: 229.97,
    itemCount: 3,
    createdAt: new Date('2024-01-22').toISOString(),
    shippingAddress: '789 Pine Rd, Chicago, IL 60601',
  },
];