/**
 * The `workflow_executions` row lifecycle around a run: creating (or upgrading
 * a dispatcher-created `queued` row) when the run starts, and cancelling a
 * queued row that will never run.
 */

import { eq, sql } from 'drizzle-orm';
import { schema } from '../db';
import type { TriggerType, WorkflowDb } from './types';

export interface StartExecutionInput {
  /** Id of a row the dispatcher already inserted as `queued`; generated by the caller otherwise. */
  id: string;
  workflowId: string;
  workflowVersion: number;
  workflowName: string;
  triggeredBy: string;
  triggerType?: TriggerType;
  triggerId?: string;
  triggerData?: Record<string, unknown>;
  totalSteps: number;
  cfWorkflowInstanceId: string;
  isTest?: boolean;
  now?: Date;
}

/**
 * Insert the execution as `running`, or, when the dispatcher already created
 * the row (retry and Test runs, so the caller had an id to navigate to),
 * upgrade it. On conflict only what the worker knows is overwritten: status,
 * start time, step total, version/name snapshot and the Cloudflare instance id.
 * Trigger data, retry lineage and the dispatcher's `executionContext` stay;
 * `isTest` is merged into the context rather than replacing it.
 */
export async function startExecutionRow(db: WorkflowDb, input: StartExecutionInput): Promise<void> {
  const now = input.now ?? new Date();
  const runs = schema.workflowExecutions;
  await db
    .insert(runs)
    .values({
      id: input.id,
      workflowId: input.workflowId,
      workflowVersion: input.workflowVersion,
      workflowName: input.workflowName,
      status: 'running',
      triggeredBy: input.triggeredBy,
      triggerType: input.triggerType || 'manual',
      triggerId: input.triggerId,
      triggerData: input.triggerData,
      startedAt: now,
      totalSteps: input.totalSteps,
      currentStepIndex: 0,
      cfWorkflowInstanceId: input.cfWorkflowInstanceId,
      executionContext: input.isTest ? { isTest: true } : undefined,
      createdAt: now,
      updatedAt: now,
    })
    .onConflictDoUpdate({
      target: runs.id,
      set: {
        status: 'running',
        startedAt: now,
        totalSteps: input.totalSteps,
        currentStepIndex: 0,
        workflowVersion: input.workflowVersion,
        workflowName: input.workflowName,
        cfWorkflowInstanceId: input.cfWorkflowInstanceId,
        updatedAt: now,
        ...(input.isTest
          ? { executionContext: sql`coalesce(${runs.executionContext}, '{}'::jsonb) || '{"isTest": true}'::jsonb` }
          : {}),
      },
    });
}

/** Flip a dispatcher-created row that will never run to `cancelled`, with the reason. */
export async function cancelQueuedExecutionRow(db: WorkflowDb, id: string, reason: string): Promise<void> {
  const now = new Date();
  await db
    .update(schema.workflowExecutions)
    .set({ status: 'cancelled', completedAt: now, error: { message: `Not run: ${reason}` }, updatedAt: now })
    .where(eq(schema.workflowExecutions.id, id));
}
