/**
 * The `workflow_executions` row lifecycle around a run: creating (or upgrading
 * a dispatcher-created `queued` row) when the run starts, and cancelling a
 * queued row that will never run.
 */

import { and, eq, sql } from 'drizzle-orm';
import { schema } from '../db';
import type { TriggerType, WorkflowDb } from './types';

export interface StartExecutionInput {
  /** Id of a row the dispatcher already inserted as `queued`; generated by the caller otherwise. */
  id: string;
  workflowId: string;
  workflowVersion: number;
  workflowName: string;
  triggeredBy: string;
  triggerType?: TriggerType;
  triggerId?: string;
  triggerData?: Record<string, unknown>;
  totalSteps: number;
  cfWorkflowInstanceId: string;
  isTest?: boolean;
  now?: Date;
}

/**
 * Insert the execution as `running`, or, when the dispatcher already created
 * the row (retry and Test runs, so the caller had an id to navigate to),
 * upgrade it. On conflict only what the worker knows is overwritten: status,
 * start time, step total, version/name snapshot and the Cloudflare instance id.
 * Trigger data, retry lineage and the dispatcher's `executionContext` stay;
 * `isTest` is merged into the context rather than replacing it.
 */
export async function startExecutionRow(db: WorkflowDb, input: StartExecutionInput): Promise<void> {
  const now = input.now ?? new Date();
  const runs = schema.workflowExecutions;
  await db
    .insert(runs)
    .values({
      id: input.id,
      workflowId: input.workflowId,
      workflowVersion: input.workflowVersion,
      workflowName: input.workflowName,
      status: 'running',
      triggeredBy: input.triggeredBy,
      triggerType: input.triggerType || 'manual',
      triggerId: input.triggerId,
      triggerData: input.triggerData,
      startedAt: now,
      totalSteps: input.totalSteps,
      currentStepIndex: 0,
      cfWorkflowInstanceId: input.cfWorkflowInstanceId,
      executionContext: input.isTest ? { isTest: true } : undefined,
      createdAt: now,
      updatedAt: now,
    })
    .onConflictDoUpdate({
      target: runs.id,
      set: {
        status: 'running',
        startedAt: now,
        totalSteps: input.totalSteps,
        currentStepIndex: 0,
        workflowVersion: input.workflowVersion,
        workflowName: input.workflowName,
        cfWorkflowInstanceId: input.cfWorkflowInstanceId,
        updatedAt: now,
        ...(input.isTest
          ? { executionContext: sql`coalesce(${runs.executionContext}, '{}'::jsonb) || '{"isTest": true}'::jsonb` }
          : {}),
      },
    });
}

/**
 * The run paused on a step that waits for input (an approval): `running` →
 * `waiting_for_input`. Only a `running` row moves, so a run cancelled in the
 * meantime stays cancelled, and only while that step's row is itself still
 * waiting, so a replay after the input arrived cannot flip the run back.
 * Returns whether the row moved.
 */
export async function markExecutionWaiting(db: WorkflowDb, id: string, waitingStepIndex: number): Promise<boolean> {
  const runs = schema.workflowExecutions;
  const steps = schema.workflowExecutionSteps;
  const updated = await db
    .update(runs)
    .set({ status: 'waiting_for_input', updatedAt: new Date() })
    .where(
      and(
        eq(runs.id, id),
        eq(runs.status, 'running'),
        sql`exists (select 1 from ${steps} where ${steps.executionId} = ${id} and ${steps.stepIndex} = ${waitingStepIndex + 1} and ${steps.status} = 'waiting_for_input')`,
      ),
    )
    .returning({ id: runs.id });
  return updated.length > 0;
}

/**
 * The input arrived (or the wait expired): `waiting_for_input` → `running`.
 * Never touches any other status, so a cancelled run is not revived.
 */
export async function markExecutionResumed(db: WorkflowDb, id: string): Promise<boolean> {
  const runs = schema.workflowExecutions;
  const updated = await db
    .update(runs)
    .set({ status: 'running', updatedAt: new Date() })
    .where(and(eq(runs.id, id), eq(runs.status, 'waiting_for_input')))
    .returning({ id: runs.id });
  return updated.length > 0;
}

/** Flip a dispatcher-created row that will never run to `cancelled`, with the reason. */
export async function cancelQueuedExecutionRow(db: WorkflowDb, id: string, reason: string): Promise<void> {
  const now = new Date();
  await db
    .update(schema.workflowExecutions)
    .set({ status: 'cancelled', completedAt: now, error: { message: `Not run: ${reason}` }, updatedAt: now })
    .where(eq(schema.workflowExecutions.id, id));
}
