/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/[id].styles`; params?: Router.UnknownInputParams; } | { pathname: `/add-account.styles`; params?: Router.UnknownInputParams; } | { pathname: `/add-account`; params?: Router.UnknownInputParams; } | { pathname: `/authorisation`; params?: Router.UnknownInputParams; } | { pathname: `/compose.styles`; params?: Router.UnknownInputParams; } | { pathname: `/compose`; params?: Router.UnknownInputParams; } | { pathname: `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/no-workspace`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/sso-callback`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/contact/[id].styles`; params?: Router.UnknownInputParams; } | { pathname: `/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/contact/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/[id].styles`; params?: Router.UnknownOutputParams; } | { pathname: `/add-account.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/add-account`; params?: Router.UnknownOutputParams; } | { pathname: `/authorisation`; params?: Router.UnknownOutputParams; } | { pathname: `/compose.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/compose`; params?: Router.UnknownOutputParams; } | { pathname: `/index.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/no-workspace`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/sso-callback`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/contact/[id].styles`; params?: Router.UnknownOutputParams; } | { pathname: `/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/contact/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/[id].styles${`?${string}` | `#${string}` | ''}` | `/add-account.styles${`?${string}` | `#${string}` | ''}` | `/add-account${`?${string}` | `#${string}` | ''}` | `/authorisation${`?${string}` | `#${string}` | ''}` | `/compose.styles${`?${string}` | `#${string}` | ''}` | `/compose${`?${string}` | `#${string}` | ''}` | `/index.styles${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/no-workspace${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/sso-callback${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/contact/[id].styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/[id].styles`; params?: Router.UnknownInputParams; } | { pathname: `/add-account.styles`; params?: Router.UnknownInputParams; } | { pathname: `/add-account`; params?: Router.UnknownInputParams; } | { pathname: `/authorisation`; params?: Router.UnknownInputParams; } | { pathname: `/compose.styles`; params?: Router.UnknownInputParams; } | { pathname: `/compose`; params?: Router.UnknownInputParams; } | { pathname: `/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/no-workspace`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/sso-callback`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/contact/[id].styles`; params?: Router.UnknownInputParams; } | `/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/contact/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/contact/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
