export { PersonalApiClient, PersonalApiClientError } from './client';
export type {
  ApiError,
  CreateDraftBody,
  DataResponse,
  ForwardMessageBody,
  ListMessagesParams,
  ListResponse,
  MailAccount,
  MailAttachment,
  MailDraft,
  MailEmailAddress,
  MailLabel,
  MailMessage,
  MeResponse,
  PaginationMeta,
  PatchMessageBody,
  PersonalAccount,
  PushTokenResult,
  RegisterPushTokenBody,
  ReplyMessageBody,
  SendMessageBody,
  UnreadCount,
  UpdateDraftBody,
  WeldmailCheckResult,
  WeldmailDomain,
  WeldmailReserveResult,
} from './types';
