/**
 * Grid column config for the People page.
 *
 * Mirrors the Companies grid pattern: the name column reads `displayName`
 * unconditionally. People can be standalone individuals (formerly b2c
 * customers) or affiliated with one or more companies via person_companies.
 */

import {
  User,
  Mail,
  Phone,
  CircleCheck,
  Building,
  Briefcase,
  Star,
  Target,
  Hash,
  Globe,
  ExternalLink,
  Calendar,
  Clock,
  Tag,
  ShieldCheck,
} from 'lucide-react';
import type { Person } from '@weldsuite/core-api-client/schemas/people';
import {
  EntityGridConfig,
  GridColumnDef,
  StatusStyle,
} from '@/components/entity-grid';

export const personStatusConfig: Record<string, StatusStyle> = {
  active: { label: 'Active', color: 'text-emerald-700 dark:text-emerald-400', bg: 'bg-emerald-50 dark:bg-emerald-950' },
  inactive: { label: 'Inactive', color: 'text-gray-600 dark:text-muted-foreground', bg: 'bg-gray-100 dark:bg-secondary' },
  left_company: { label: 'Left Company', color: 'text-amber-700 dark:text-amber-400', bg: 'bg-amber-50 dark:bg-amber-950' },
  prospect: { label: 'Prospect', color: 'text-violet-700 dark:text-violet-400', bg: 'bg-violet-50 dark:bg-violet-950' },
  churned: { label: 'Churned', color: 'text-red-700 dark:text-red-400', bg: 'bg-red-50 dark:bg-red-950' },
};

function getPersonAvatar(person: Person): string | undefined {
  if (person.avatarUrl) return person.avatarUrl;
  // Gravatar fallback when there's an email
  if (person.email) {
    return `https://www.gravatar.com/avatar/${encodeURIComponent(person.email.toLowerCase())}?d=mp&s=64`;
  }
  return undefined;
}

export const personColumns: GridColumnDef<Person>[] = [
  {
    id: 'name',
    name: 'Name',
    type: 'company',
    width: 260,
    icon: User,
    visible: true,
    editable: false,
    sortable: true,
    favoriteField: 'isFavorite',
    // Read displayName directly — no firstName/lastName branching.
    getValue: (p) => p.displayName,
  },
  {
    id: 'title',
    name: 'Title',
    type: 'text',
    width: 180,
    icon: Briefcase,
    visible: true,
    editable: true,
    sortable: true,
    getValue: (p) => p.title ?? '',
    setValue: (_p, v) => ({ title: (v as string) || undefined }),
  },
  {
    id: 'department',
    name: 'Department',
    type: 'text',
    width: 160,
    icon: Building,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.department ?? '',
    setValue: (_p, v) => ({ department: (v as string) || undefined }),
  },
  {
    id: 'email',
    name: 'Email',
    type: 'email',
    width: 220,
    icon: Mail,
    visible: true,
    editable: true,
    sortable: true,
    getValue: (p) => p.email ?? '',
    setValue: (_p, v) => ({ email: (v as string) || undefined }),
  },
  {
    id: 'directPhone',
    name: 'Phone',
    type: 'phone',
    width: 150,
    icon: Phone,
    visible: true,
    editable: true,
    sortable: true,
    getValue: (p) => p.directPhone ?? '',
    setValue: (_p, v) => ({ directPhone: (v as string) || undefined }),
  },
  {
    id: 'mobilePhone',
    name: 'Mobile',
    type: 'phone',
    width: 150,
    icon: Phone,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.mobilePhone ?? '',
    setValue: (_p, v) => ({ mobilePhone: (v as string) || undefined }),
  },
  {
    id: 'status',
    name: 'Status',
    type: 'single-select',
    width: 140,
    icon: CircleCheck,
    visible: true,
    editable: true,
    sortable: true,
    options: ['active', 'inactive', 'left_company', 'prospect', 'churned'],
    selectConfig: personStatusConfig,
    getValue: (p) => p.status,
    setValue: (_p, v) => ({ status: v as string }),
  },
  {
    id: 'role',
    name: 'Role',
    type: 'text',
    width: 160,
    icon: ShieldCheck,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.role ?? '',
    setValue: (_p, v) => ({ role: (v as string) || undefined }),
  },
  {
    id: 'isSupplier',
    name: 'Supplier',
    type: 'checkbox',
    width: 110,
    icon: Star,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.isSupplier,
    setValue: (_p, v) => ({ isSupplier: !!v }),
  },
  {
    id: 'isLead',
    name: 'Lead',
    type: 'checkbox',
    width: 90,
    icon: Star,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.isLead,
    setValue: (_p, v) => ({ isLead: !!v }),
  },
  {
    id: 'isDecisionMaker',
    name: 'Decision Maker',
    type: 'checkbox',
    width: 150,
    icon: ShieldCheck,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.isDecisionMaker ?? false,
    setValue: (_p, v) => ({ isDecisionMaker: !!v }),
  },
  {
    id: 'isBillingContact',
    name: 'Billing Contact',
    type: 'checkbox',
    width: 150,
    icon: ShieldCheck,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.isBillingContact ?? false,
    setValue: (_p, v) => ({ isBillingContact: !!v }),
  },
  // Hidden / surfaced via "Add column"
  {
    id: 'lifecycleStage',
    name: 'Lifecycle Stage',
    type: 'text',
    width: 160,
    icon: Target,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.lifecycleStage ?? '',
    setValue: (_p, v) => ({ lifecycleStage: (v as string) || undefined }),
  },
  {
    id: 'source',
    name: 'Source',
    type: 'text',
    width: 150,
    icon: Target,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.source ?? '',
    setValue: (_p, v) => ({ source: (v as string) || undefined }),
  },
  {
    id: 'leadScore',
    name: 'Lead Score',
    type: 'number',
    width: 120,
    icon: Hash,
    visible: false,
    editable: false,
    sortable: true,
    getValue: (p) => p.leadScore ?? null,
  },
  {
    id: 'linkedinUrl',
    name: 'LinkedIn',
    type: 'url',
    width: 200,
    icon: ExternalLink,
    visible: false,
    editable: true,
    sortable: false,
    getValue: (p) => p.linkedinUrl ?? '',
    setValue: (_p, v) => ({ linkedinUrl: (v as string) || undefined }),
  },
  {
    id: 'preferredLanguage',
    name: 'Language',
    type: 'text',
    width: 130,
    icon: Globe,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.preferredLanguage ?? '',
    setValue: (_p, v) => ({ preferredLanguage: (v as string) || undefined }),
  },
  {
    id: 'tags',
    name: 'Tags',
    type: 'multi-select',
    width: 200,
    icon: Tag,
    visible: false,
    editable: true,
    sortable: false,
    getValue: (p) => p.tags ?? [],
    setValue: (_p, v) => ({ tags: (v as string[]) ?? [] }),
  },
  {
    id: 'ownerId',
    name: 'Owner',
    type: 'text',
    width: 160,
    icon: Briefcase,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.ownerId ?? '',
    setValue: (_p, v) => ({ ownerId: (v as string) || undefined }),
  },
  {
    id: 'lastContactedAt',
    name: 'Last Contacted',
    type: 'date',
    width: 150,
    icon: Calendar,
    visible: false,
    editable: false,
    sortable: true,
    getValue: (p) => p.lastContactedAt ?? null,
  },
  {
    id: 'nextFollowUpDate',
    name: 'Next Follow-up',
    type: 'date',
    width: 150,
    icon: Clock,
    visible: false,
    editable: true,
    sortable: true,
    getValue: (p) => p.nextFollowUpDate ?? null,
    setValue: (_p, v) => ({ nextFollowUpDate: v as string }),
  },
  {
    id: 'createdAt',
    name: 'Created At',
    type: 'date',
    width: 150,
    icon: Calendar,
    visible: false,
    editable: false,
    sortable: true,
    getValue: (p) => p.createdAt,
  },
];

export const personGridConfig: EntityGridConfig<Person> = {
  entityName: 'Person',
  entityNamePlural: 'People',
  columns: personColumns,
  getEntityId: (p) => p.id,
  getEntityName: (p) => p.displayName,
  getEntityInitials: (p) => {
    const parts = p.displayName.split(/\s+/).filter(Boolean);
    if (parts.length >= 2) return (parts[0]!.charAt(0) + parts[parts.length - 1]!.charAt(0)).toUpperCase();
    return p.displayName.charAt(0).toUpperCase();
  },
  getEntityAvatar: (p) => getPersonAvatar(p),
  getEntitySubtitle: (p) => p.title ?? undefined,
  statusField: 'status',
  statusConfig: personStatusConfig,
  allowCustomColumns: true,
  enableCalculations: true,
  enableInlineEditing: true,
  enableRowSelection: true,
  enableExport: true,
  enableImport: false,
};
